plugins/monitoring/app/models/monitoring/alarm.rb
plugins/monitoring/app/views/monitoring/alarms/_list_row.html.haml

This allows us to show the alarm's description with template variables filled in by Monasca, and potentially avoids a call to the alarm-definition API.

Read alarm's description from alarm API instead of alarm-definition API

---

plugins/identity/app/helpers/identity/projects_helper.rb
plugins/identity/app/views/identity/projects/groups/_group.html.haml
plugins/identity/app/views/identity/projects/members/_member.html.haml
plugins/identity/config/locales/en.yml

for more clarity we label the role names. most important for role `admin` to be identified as 'Keystone Admininistrator'
Happy Fighting over the label names 😄 💥 
@edda: okay? 
@urfuwo FYI

[identity] add translation to role names

---

plugins/networking/app/controllers/networking/networks_controller.rb
plugins/networking/app/views/networking/networks/index.html.haml

the list for the cloud_network_admin is getting too long, so paginate
needs activated pagination in neutron, see https://github.com/sapcc/openstack-helm/commit/f3c49865c8c59e0431b499228ea2db4cbeb0236b

[networking] add pagination to networks

---

plugins/compute/app/views/compute/instances/new_floatingip.html.haml
plugins/loadbalancing/app/views/loadbalancing/loadbalancers/new_floatingip.html.haml

Users are presented a dialog to create a floating ips, when floating IPs exhausted in the project. 
When a user does that, the IP is not assigned. Quite miss-leading when using it.

textual change. in case no floating IPs available.

---

plugins/compute/app/controllers/compute/instances_controller.rb

I could create an instance without these lines and without having a special nova role
@andypf please have a look

remove unused extra policy_default_param

---

app/helpers/application_helper.rb
plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/models/compute/usage.rb
plugins/compute/app/services/service_layer/compute_service.rb
plugins/compute/app/views/compute/instances/_item.html.haml
plugins/compute/app/views/compute/instances/index.html.haml
plugins/compute/config/policy.json
plugins/compute/lib/compute/driver/fog.rb

added pagination + owning project
@edda / @andypf : ok with you?
would it be good to be able to turn this on/off as cloud_compute_admin or adding a flag/warning that such view is not limited to the project I am currently scoped to? same question applies to existing (for zones, flavors, images, networks ...) and coming super admin views

[compute] compute_cloud_admin can view all instances

---

plugins/resource_management/app/controllers/resource_management/domain_admin_controller.rb
plugins/resource_management/app/views/resource_management/domain_admin/review_package_request.html.haml
plugins/resource_management/app/views/resource_management/domain_admin/review_request.html.haml

Whenever a domain admin adjusts project quotas, ensure that they cannot exceed their domain quota allocation.

make domain quotas binding

---

plugins/dns_service/config/policy.json
plugins/identity/config/initializers/constants.rb

reflect https://github.com/sapcc/openstack-helm/commit/f242605e111ec66aff1b4e2cc9132d19991d719d
better merge after the policy in designate backend has been rolled out, to not get confused over not working read-only

[dns] add dns_viewer and make policy more readable

---

app/assets/stylesheets/_monsoon_theme.scss
plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/views/compute/instances/show.html.haml

admins get here from looking up directly, so can't trigger actions
at the list
e.g. to delete stuck instances found via object lookup server
@edda : what do you think? is this pretty enough?

[compute] add instance action tab to show for admins

---

plugins/resource_management/app/controllers/resource_management/domain_admin_controller.rb

@majewsky Please take a look. We discovered an error, if a service is not available then @domain.find_resource returns nil and it bangs.

[resource_management] bugfix in domain_admin_controller

---

plugins/identity/config/initializers/constants.rb

which is end-user assignable (permission to see tenant-metrics we have chosen to make available)

Add Maia's monitoring_viewer role

---

config/application.rb

The latest ruby prometheus client needs the label builder defined slightly different.
Also the latency metric is now a histogram instead of a summary. The prometheus graphs need to be changed to work again. Somebody needs to take care of this after merging this PR.
Also I reduced the label cardianlity on the latency metrics, now we only record the request method and the plugin.

fix metric collection

---

plugins/compute/app/views/compute/instances/new_snapshot.html.haml

@edda we have all linux vms snapshots working, hence refinement of the alert info.

(snapshots) refine notification. just windows not working.

---

Gemfile.lock
app/helpers/view_helper.rb
plugins/networking/app/assets/javascripts/networking/plugin/dhcp_agents.js.coffee
plugins/networking/app/controllers/networking/networks/dhcp_agents_controller.rb
plugins/networking/app/models/networking/dhcp_agent.rb
plugins/networking/app/services/service_layer_ng/networking_service.rb
plugins/networking/app/services/service_layer_ng/networking_services/dhcp_agent.rb
plugins/networking/app/views/networking/networks/_item.html.haml
plugins/networking/app/views/networking/networks/dhcp_agents/_dhcp_agent_item.html.haml
plugins/networking/app/views/networking/networks/dhcp_agents/_new_dhcp_agent_form.html.haml
plugins/networking/app/views/networking/networks/dhcp_agents/create.js.erb
plugins/networking/app/views/networking/networks/dhcp_agents/destroy.js.erb
plugins/networking/app/views/networking/networks/dhcp_agents/index.html.haml
plugins/networking/config/policy.json
plugins/networking/config/routes.rb

stolen from network access the js could be more functional instead of the whole reloading 🙄 
functionality provided works: add+remove dhcp agent from network as cloud_network_admin - that was a handy admin function in horizon 💀 
@andypf okay with you? feel free to improve on the js and the look 😉

DHCP agent mgmt

---

Makefile
contrib/elektra-changelog-builder/.github_changelog_generator
contrib/elektra-changelog-builder/Dockerfile
contrib/elektra-changelog-builder/Makefile

This commits adds a Docker image that includes a tool that automatically
generates changelogs.
See: https://github.com/skywinder/github-changelog-generator
This tool relies on Github metadata to generate the Changelog. This has
the advantage that it knows more than the Git history e.g. PRs,
Labels...
The here proposed workflow is to not include the generation of the
changelog into CI, but rather manually run it for each major version.
It's easy enough:
rm CHANGELOG.md
make CHANGELOG.md
Fixes #196

Adds Automatic Changelog Generation

---

plugins/compute/app/models/compute/flavor.rb

This is not working yet, but no idea why. There seems to be something horribly broken in the exception handling. For example, if I do this instead:
```ruby
begin
@service.delete_flavor(id) unless id.blank?
rescue => e
pp(e.class)
pp(e.code)
raise StandardError, 'manual error'
end
```
I see the output of the `pp()`, but the UI shows the error message from `e` rather than "manual error". WTF.

Compute::Flavor.save: do not fail when creating new flavor

---

plugins/networking/app/assets/javascripts/networking/plugin/security_group_rule.coffee
plugins/networking/app/views/networking/security_groups/rules/new.html.haml
plugins/networking/config/security_group_rule_types.yml

I previously considered a design where the user has to confirm that they read the documentation by checking a checkbox (like when agreeing to ToS), but that is probably too drastic.

discourage remote security groups

---

plugins/networking/app/controllers/networking/network_wizard_controller.rb

This is WIP because we should have documentation about this before merging.

network wizard: remove self-referential ingress rules from the default secgroup

---

plugins/identity/config/policy.json
plugins/image/config/policy.json
plugins/masterdata_cockpit/config/policy.json

This adds the necessary policy entries to support viewer roles for all plugins that were missing them: identity, images, masterdata.

Add policy rules for viewer roles

---

plugins/compute/app/controllers/compute/instances_controller.rb

Customer with only one `member` role was not allowed to create an automation for a node.
```
{"error":"You are not authorized to view this page. Please check (role assignments) if you have one of the           following roles: admin."}
```

Fix automation_script permissions typo

---

Procfile
env.sample

`--host` option is not working https://github.com/webpack/webpack-dev-server/issues/882
to overwrite the host from webpacker.yml config use `WEBPACKER_DEV_SERVER_HOST=x.x.x.x` in `.env`

Webpacker host option

---

app/controllers/concerns/error_renderer.rb
plugins/audit/spec/controllers/application_controller_spec.rb
plugins/automation/app/assets/javascripts/automation/automation.coffee
plugins/automation/app/controllers/automation/application_controller.rb
plugins/automation/app/controllers/automation/automations_controller.rb
plugins/automation/app/controllers/automation/jobs_controller.rb
plugins/automation/app/controllers/automation/nodes_controller.rb
plugins/automation/app/controllers/automation/runs_controller.rb
plugins/automation/app/views/automation/automations/_table_automations.html.haml
plugins/automation/app/views/automation/automations/_table_automations_item.html.haml
plugins/automation/app/views/automation/automations/index.html.haml
plugins/automation/app/views/automation/nodes/_form_tags.html.haml
plugins/automation/app/views/automation/nodes/_table_nodes.html.haml
plugins/automation/app/views/automation/nodes/_table_nodes_item.html.haml
plugins/automation/app/views/automation/nodes/index.html.haml
plugins/automation/app/views/automation/shared/_roles_atention_box.html.haml
plugins/automation/app/views/automation/shared/warning.html.haml
plugins/automation/config/policy.json
plugins/automation/spec/controllers/automations_controller_spec.rb
plugins/automation/spec/controllers/jobs_controller_spec.rb
plugins/automation/spec/controllers/nodes_controller_spec.rb
plugins/automation/spec/controllers/runs_controller_spec.rb
plugins/compute/app/views/compute/instances/_cloud_init_menu.html.haml
plugins/compute/config/policy.json
plugins/identity/config/initializers/constants.rb
plugins/metrics/spec/controllers/application_controller_spec.rb
plugins/resource_management/spec/controllers/application_controller_spec.rb

Automation plugin should implement a policy and repect the roles automation_admin & automation_viewer. Currently the user requires keystone admin and or members to setup and run automations.
Fixes #382

Automation policies

---

app/controllers/cache_controller.rb
config/policy.json

Fixes #397 Allow unscoped (region-wide) search for cloud_support_tools_viewer role in addition to cloud_admin

Allow unscoped search for cloud_support_tools_viewer

---

app/assets/javascripts/regions.json

ap-jp-1 is located in Toyko, ap-jp-2 in Osaka but geodata for these
region said it was the other way around.

Fix ap-jp-1 and ap-jp-2 geodata

---

plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/models/compute/remote_console.rb
plugins/compute/app/models/compute/shellinabox_console.rb
plugins/compute/app/services/service_layer/compute_service.rb
plugins/compute/app/services/service_layer/compute_services/server.rb

This PR will implement the new remote console api:
https://developer.openstack.org/api-ref/compute/?expanded=show-console-output-os-getconsoleoutput-action-detail,get-vnc-console-os-getvncconsole-action-deprecated-detail#create-remote-console
and also unify shellinabox/vnc console to generic "remote_console" function.
Also enabled MKS by default, please wait a week before rollout to ensure mks is everywhere enabled.

added generic remote console support

---

plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/services/service_layer/compute_services/server.rb
plugins/compute/app/views/compute/instances/show.html.haml

this adds support for for getconsoleoutput api of nova:
https://developer.openstack.org/api-ref/compute/?expanded=show-console-output-os-getconsoleoutput-action-detail,get-vnc-console-os-getvncconsole-action-deprecated-detail#show-console-output-os-getconsoleoutput-action
Please feel free to improve it (like download the data only if clicked on "serial-log" or some kind of syntax highlighting ^^

added support for serial console log of nova

---

plugins/networking/app/controllers/networking/networks_controller.rb

Display network name on network create in the UI, currently the subnet name is displayed instead.

When creating a network display network name instead of subnet name

---

plugins/object_storage/app/views/object_storage/application/_object_list_entry.html.haml

As inline rendering of content is now html encoded, only Content-Types
of type `text/*` should be handled so. Otherwise Content Disposition is Download.

object store: inline content only for text/*

---

app/assets/javascripts/jquery.ajax_paginate.coffee

The pagination fetcher triggered by the search field had following issue "Maximum call stack size exceeded" coming from the application.js file. This is due that the loadAllOnSearch is being called continuously until end of stack. With a delay and triggering the fetcher once fix the problem.

collect pagination data once with 0,5 sec delay when checking completed

---

plugins/compute/app/controllers/compute/instances_controller.rb

should fix remote console problems with baremetal servers since the compute-nodes are called "nova-compute-ironic-bbXX"

fix remote console (shellinabox) detection for new ironic conductors

---

plugins/dns_service/app/models/dns_service/recordset.rb

when creating DNS mx records sets for proper syntax.
WRONG! Elektra accepts these as valid:
`10 smtpdem02.mail.net, 10 smtpdem01.mail.net.`
but it should be:
`10 smtpdem02.mail.net., 10 smtpdem01.mail.net.`

extended cname check for mx

---

plugins/identity/app/controllers/identity/projects_controller.rb
plugins/identity/app/views/identity/projects/_wizard_steps.html.haml
plugins/identity/spec/controllers/projects_controller_spec.rb
plugins/resource_management/app/services/service_layer/resource_management_service.rb
plugins/resources/app/assets/stylesheets/resources/_application.scss
plugins/resources/app/controllers/resources/application_controller.rb
plugins/resources/app/javascript/app/components/applications/init_project.jsx
plugins/resources/app/javascript/app/components/applications/main.jsx
plugins/resources/app/javascript/app/components/init_project.jsx
plugins/resources/app/javascript/app/components/loader.jsx
plugins/resources/app/javascript/app/components/overview.jsx
plugins/resources/app/javascript/app/constants.js
plugins/resources/app/javascript/app/containers/init_project.js
plugins/resources/app/javascript/app/init.js
plugins/resources/app/javascript/app/scope.js
plugins/resources/app/javascript/app/utils.js
plugins/resources/app/services/service_layer/resources_service.rb
plugins/resources/app/views/resources/application/init_project.html.haml
plugins/resources/app/views/resources/application/show.html.haml
plugins/resources/config/policy.json
plugins/resources/config/routes.rb

The new implementation only requests quotas within auto-approval limits, so no request workflow is needed.
The screenshot shows an example situation where the domain has run out of Block Storage quota, so the respective package cannot be selected by the user. (The tooltip is shown because I hovered over the Block Storage package while taking the screenshot.)

new wizard step: Initialize Project Resources

---

docker/Dockerfile

Precompile assets including webpacker packs 
We use dummy master.key to workaround the fact that assets:precompile needs them but we don't want the real master.key to be built into the container. The MONSOON_RAILS_SECRET_TOKEN should be injected as env var when starting the container.

Fix public-image step on the pipeline

---

plugins/identity/app/views/identity/projects/_wizard_steps.html.haml
plugins/networking/app/controllers/networking/network_wizard_controller.rb
plugins/networking/app/views/networking/network_wizard/skip_wizard.js.erb
plugins/networking/app/views/networking/network_wizard/skip_wizard_confirm.html.haml
plugins/networking/config/routes.rb

For non-standard custom network setups so that these projects can get rid of the project wizard.

Network wizard skip option

---

config/routes.rb

There were some concerns that adding this redirect would break other routes but in my local tests it works and I couldn't find any broken project plugin links.

redirect /:domain_id/:project_id -> /:domain_id/:project_id/home

---

plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/views/compute/instances/_item.html.haml
plugins/compute/app/views/compute/instances/console_log.html.haml
plugins/compute/app/views/compute/instances/show.html.haml
plugins/compute/config/routes.rb

this will remove the server info tab 'serial log' and instead puts an
option to the advanced task menu of a server. Also makes calls
to os-getConsoleOutput deliberatily and not just by opening
the server info modal.

move serial log to modal, fixes #480

---

config/webpacker.yml
yarn.lock

In some cases yarn fails with `Incorrect integrity when fetching from the cache` that is caused by old lockfile entries (more than a year ago?) that don't have the integrity field present.
To prevent the `Incorrect integrity` error I migrated the `yarn.lock`. Any entry has now an integrity field. 
See also: https://github.com/yarnpkg/yarn/issues/7584

migrate yarn log with integrity field

---

plugins/resources/app/javascript/app/components/overview.jsx

Hi, I noticed an additional semicolon in the "Manage Project Resources" > "Availability Zones" page.
Hope this fixes it ;)
Cheers,
Maurice

fix formatting resources overview

---

plugins/loadbalancing/app/controllers/loadbalancing/loadbalancers/listeners/l7policies_controller.rb
plugins/loadbalancing/app/controllers/loadbalancing/loadbalancers/listeners_controller.rb
plugins/loadbalancing/app/controllers/loadbalancing/loadbalancers/pools_controller.rb
plugins/loadbalancing/app/controllers/loadbalancing/loadbalancers_controller.rb

This fixes displaying loadbalancer information since neutron used to ignore the fields=
attribute as well as l7policy display since loadbalancer_id is not used.

fix loadbalancing display when using octavia proxy

---

plugins/shared_filesystem_storage/app/controllers/shared_filesystem_storage/cloud_admin/pools_controller.rb
plugins/shared_filesystem_storage/app/services/service_layer/shared_filesystem_storage_service.rb
plugins/shared_filesystem_storage/app/services/service_layer/shared_filesystem_storage_services/share.rb
plugins/shared_filesystem_storage/app/views/shared_filesystem_storage/cloud_admin/pools/_item.html.haml
plugins/shared_filesystem_storage/app/views/shared_filesystem_storage/cloud_admin/pools/index.html.haml

we will get more than one type, also in production soon and want to have an overview which pool is related to what type

[shared_filesystem] show cloud admin pools for all types

---

app/assets/javascripts/dialogs.js.coffee

Closing the confirm dialog when the main modal view still open removes the class "modal-open" from body which prevent the main modal view to be scrolled again

Fixed main modal view scroll when comming from a infoDialog

---

plugins/lbaas2/app/models/lbaas2/healthmonitor.rb
plugins/lbaas2/app/models/lbaas2/l7policy.rb
plugins/lbaas2/app/models/lbaas2/l7rule.rb
plugins/lbaas2/app/models/lbaas2/listener.rb
plugins/lbaas2/app/models/lbaas2/loadbalancer.rb
plugins/lbaas2/app/models/lbaas2/member.rb
plugins/lbaas2/app/models/lbaas2/pool.rb

Remove not editable attribute admin_state_up to prevent to send nil attribute to the backend
Fixes #791

[lbaas2]: remove not editable attribute admin_state_up

---

plugins/block_storage/config/policy.json

volume types can be listed by `volume_viewer`, it should not fall back to require the `admin` role
fixes 401 with only volume_admin
follows 1e165a1c133d77be9787c595dd8bdc40eae7f1cf

define policy for cinder volume types

---

plugins/compute/app/assets/stylesheets/compute/_application.scss
plugins/compute/app/views/compute/instances/_item_actions.html.haml
plugins/compute/app/views/compute/instances/confirm_hard_reset.html.haml
plugins/compute/app/views/compute/instances/console.html.haml
plugins/compute/app/views/compute/instances/pre_hard_reset.js.erb
plugins/compute/app/views/layouts/compute/console.html.haml

Originally, we were using a VNC session, but that is switched to an
MKS one since some time now.
And for ironic, we do use some different service altogether.
So we better name everything technology agnostic in order to avoid
confusion

Rename VNC console to Web Console

---

plugins/resources/app/javascript/app/components/autoscaling/config_ng/subscope_item.js
plugins/resources/app/javascript/app/components/autoscaling/config_ng/subscopes.js

Long story short...
tempMinfree was created once when the modal view was loaded. 
https://github.com/sapcc/elektra/blob/master/plugins/resources/app/javascript/app/components/autoscaling/config_ng/subscope_item.js#L26
When switching the different autoscaling projects react.useffect was triggered updating the minFree in the State with the NOT updated tempMinFree set when the modal view was opened for first time. The trigger was not the tempMinFree itself but the unit.
https://github.com/sapcc/elektra/blob/master/plugins/resources/app/javascript/app/components/autoscaling/config_ng/subscope_item.js#L48
I didn't see any benefit of using this tempMinFree so I removed it and instead the state is being updated directly. @andypf can do a double check before merging.
cc @majewsky 
fixes #992

[resources] Autoscaling fix

---

plugins/compute/app/views/compute/instances/show.html.haml

The prometheus API query uses the virtual instance `name`, which can cause errors because they are not unique - use the OpenStack `instance_uuid` instead.

[compute instances][VMware vm tools] fix: prometheus query with instance_uuid

---

plugins/compute/app/views/compute/instances/show.html.haml

We will offload the global `vrops_` metrics from `prometheus-infra-collector` starting April 19 at 9am CET. The data should then be queried by `prometheus-vmware`. No further changes are necessary - no certificates or the like. 
We will confirm in this PR when the move is complete.

[compute instances] new prometheus url on April 19, 9AM CET

---

plugins/compute/app/views/compute/instances/show.html.haml

Updated the query to Prometheus to filter out right-sizing recommendations for VMs larger than 256GiB.

[compute instances] exclude big VMs from the right-sizing recommendation

---

plugins/identity/config/initializers/constants.rb
plugins/identity/config/locales/en.yml
plugins/object_storage/config/policy.json

* Introduce `object_storage_viewer` policy and allow read access
* blacklist `cloud_objectstore_*` roles
* locals for new roles
TODO: After rollout and migration remove references to `swiftoperator`

Introduce new Objectstore Roles

---

plugins/lbaas2/app/javascript/widgets/app/components/l7Rules/EditL7Rule.jsx

Enduser is forced to change the compare type

[lbaas2]: prevent user save a regex l7rule when editing

---

e2e/cypress/integration/member/instances.js
e2e/cypress/integration/member/shared_object_storage.js
plugins/compute/app/views/compute/instances/new_snapshot.html.haml
plugins/identity/config/initializers/constants.rb
plugins/object_storage/app/views/object_storage/entry/howtoenable.html.haml

Allow new roles for Swift `objectstore_viewer` and `objectstore_admin` in Elektra.
Reference new role in description of services.

Objectstore Roles

---

plugins/keppel/app/javascript/widgets/app/components/images/row.jsx

I currently don't have a functioning dev setup for Elektra, so I can't verify this myself. Can one of you please quickly check if this has the desired effect of allowing long label lines like these to break?
For testing purposes, I've provided a suitable image in qa-de-1 in the cc-demo/alpine repo.

keppel: allow long label lines to break

---

plugins/lbaas2/app/models/lbaas2/member.rb

Octavia pool members can have a weight between 0 and 256.

[lbaas2] Fix member weight range. Member weights can be 0.

---

plugins/tools/app/javascript/widgets/limes/actions/limes.js

The old endpoint URL will go away probably next week.

tools: update endpoint URL for limes rate-scrape-errors

---

package.json
yarn.lock

This way, it should not randomly break when a new Juno version is tagged.

pull Juno dependency by tag version instead of by "latest"

---

plugins/identity/config/initializers/constants.rb
plugins/identity/config/locales/en.yml
plugins/object_storage/config/policy.json
plugins/object_storage_ng/config/policy.json

The roles `swiftoperator` and `swiftreseller` were purged from OpenStack identity. Cleanup in Elektra as well.

[objectstore] cleanup deleted Swift roles

---

plugins/lbaas2/app/controllers/lbaas2/loadbalancers/pools/healthmonitors_controller.rb
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/EditHealthMonitor.jsx
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/HealthmonitorDetails.jsx
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/NewHealthMonitor.jsx
plugins/lbaas2/app/models/lbaas2/healthmonitor.rb
plugins/lbaas2/spec/controllers/factories/factories.rb

[lbaas]: changed max_retries to max_retries_down

---

plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/EditHealthMonitor.jsx
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/HealthMonitor.jsx
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/NewHealthMonitor.jsx

Customers rarely use the dashboard and the CLI at the same time, so it's better to keep the wording true to the concepts used on the dashboard.
In #944 we decided to display members in state ERROR as OFFLINE. It is true that the operating_status of the members is set to ERROR in Octavia, but it is marked as OFFLINE in Elektra.

[lbaas] Fix wording: Members are marked as OFFLINE

---

plugins/shared_filesystem_storage/app/services/service_layer/shared_filesystem_storage_services/share_rule.rb

new method was added with microversion 2.45, see
https://docs.openstack.org/api-ref/shared-file-system/#list-share-access-rules
benefit: since audit middleware ignores GET requests, we get less audit spam

[manila] change listing share access rules from POST to GET

---

plugins/keppel/app/javascript/widgets/app/components/images/details.jsx
plugins/keppel/app/javascript/widgets/app/components/images/list.jsx
plugins/keppel/app/javascript/widgets/app/components/images/row.jsx

These names serve Trivy data instead of Clair data now. The Trivy-specific names were only used to ensure a smooth migration, and are due for removal when the Clair integration goes away.
The only Trivy-specific name that remains is for the `trivy_report` endpoint, since Trivy reports truly have a different format than Clair reports.

keppel: flip vulnerability status queries back to canonical names

---

plugins/keppel/app/javascript/widgets/app/components/repositories/list.jsx

This is more logical since images are the first number in the row and also use at least a tiny amount of storage while tags are almost free.
@majewsky what do you think?

keppel: change sort order of the contains column to prefer images over tags

---

plugins/compute/app/views/compute/instances/new.html.haml

The prefix `hv` is used to identify hypervisor flavors, which are also baremetal.

Handle "^hv" for hypervisors in new instances

---

plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/HealthmonitorDetails.jsx
plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/NewHealthMonitor.jsx

A follow-up for the #1175 to avoid a potential user confusion.

[octavia] add a "Max Retries" note to a health monitor UI

---

plugins/resources/app/javascript/widgets/app/components/details/modal.jsx
plugins/resources/app/javascript/widgets/app/components/edit.jsx
plugins/resources/app/javascript/widgets/app/components/resource_editor.jsx

@VoigtS fyi
Context for the UI team: The main concern is that we need to block editing of quotas for resources with automatic quota distribution. We already had some affordances for this because of an earlier, unrealized project called "centralized quota distribution", where quota editing was blocked in certain situations. So this PR mostly just boils down to removing the "in certain situations" part of the check and updating the messaging.

plugins/resources: prepare messaging for automatic quota distribution

---

config/navigations/cloud_admin_navigation.rb

Cluster UI: Rename `Resource Management` to `Cluster Resources Administration`.
The previous naming caused confusion for the support team, because it collided with the project level naming of the UI.

[Resources] Distinguish cluster UI naming

---

config/navigations/cloud_admin_navigation.rb

The cloud admin UI was not present in elektra. The cloud admin nav item still had a deprecated service check to the old resource UI. I changed this to an plugin availability check, so that the admin UI actually shows up in the UI.

Adjusting cluster admin UI link reference

---

plugins/shared_filesystem_storage/app/services/service_layer/shared_filesystem_storage_services/replica.rb

according to API spec the values should be `null`, not `true`
e.g. see https://docs.openstack.org/api-ref/shared-file-system/#resync-share-replica
promote received additional optional arguments (like quiesce_wait_time see https://docs.openstack.org/api-ref/shared-file-system/#promote-share-replica) and sending true is being rejected now by the manila api validation

[shared_filesystem_storage] correct replica actions

---

plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_project_details.html.haml

This PR addresses a `NoMethodError` bug in the Masterdata plugin. The issue occurs when the billing API fails to respond or returns an error, causing the controller's flow to be interrupted. As a result, the method responsible for fetching the project data is never executed, leading to the standard Rails error "NoMethodError" being displayed in the view.
The issue has been resolved by using the safe navigation operator (`&.`), which gracefully handles `nil` values without raising an exception. Specifically, `project.name` has been replaced with `project&.name`, ensuring that the view does not break when `project` is `nil`.
This fix ensures a smoother user experience by preventing unexpected errors and maintaining the intended flow in the application.

fix(masterdata): do not show no method error if billing API is down

---

plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/helpers/compute/instances_helper.rb
plugins/compute/app/models/compute/server.rb

This PR addresses two key issues that emerged after reworking the process of attaching multiple fixed and floating IPs to an instance:
1.	Floating IP Detachment Error: The detachment process for floating IPs stopped functioning because the Floating IP was missing its ID in the relevant map. This ID is crucial for successfully detaching the Floating IP. The issue has been resolved by ensuring the ID is correctly included.
2.	View Update Errors: The view was not updating correctly after attaching or detaching a Floating IP due to a delay. Even after reloading, the changes were not immediately reflected in the instance. This was fixed by manually adding or removing the floating IP entry in the instance addresses, ensuring the view updates as expected.

fix(compute): load floating ip to get the id

---

plugins/networking/app/controllers/networking/security_groups_controller.rb
plugins/networking/app/javascript/widgets/security_groups/components/security_groups/list.jsx
plugins/networking/app/services/service_layer/networking_services/security_group.rb

will load all security groups beyond the 500 items limit
this is a fix that works without larger rewrite of the code, just use the marker option to load all items on server side, than the user can use the search on client side to find the item. 
But it comes with a grain of salt 
1. it can be a problem if more than 1 or 2k Security Groups are found
2. the Api is not that fast to deliver the items if the count is beyond 500 
- adjust the loading funktion in the controller to load all security groups with marker if more than 500 are found
- adjust view to show the count of all security groups
- disable the new button if loading is in progress
- add api docu to service layer
- Issue 1: #1395

fix(security groups): handle 500 items limit

---

plugins/dns_service/app/controllers/concerns/create_zones_helper.rb
plugins/dns_service/app/controllers/dns_service/create_zone_wizard_controller.rb
plugins/dns_service/app/controllers/dns_service/request_zone_wizard_controller.rb
plugins/identity/app/controllers/identity/domains/create_wizard_controller.rb

* The whole DNS quota-editing thing has been either superfluous or broken since May, when Limes stopped supporting quota editing.
* After this, the only thing that's left is to explicitly sync projects after a new project is created. This is something that Limes does on its own, anyway; the explicit sync is just to shorten the wait time from max. 3 minutes to a few seconds. Since we don't commonly have domain admins create projects that need to be ready to use by the same person immediately afterwards, I think we can live with the max. 3 minutes delay.
If you approve this, please also merge https://github.com/sapcc/helm-charts/pull/7065.

remove everything that needs cloud_resource_admin permissions

---

README.md
app/views/layouts/modal.html.haml
plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/views/compute/instances/new_snapshot.html.haml
plugins/compute/spec/controllers/instances_controller_spec.rb
plugins/networking/app/controllers/networking/routers_controller.rb
plugins/networking/app/controllers/networking/widgets_controller.rb
plugins/networking/spec/controllers/floating_ips_controller_spec.rb
plugins/networking/spec/controllers/networks/subnets_controller_spec.rb
plugins/networking/spec/controllers/networks_controller_spec.rb

These were partially already broken because Juno plugins do not see @quota_data, or they are utterly superfluous because there is no action the user can take to mitigate low quota anyway.

remove all remaining usages of the old @quota_data mechanism

---

app/views/application/_breadcrumb.html.haml

This PR introduces a check for the WebConsole icon in the Topbar, allowing us to disable it in the context of Bedrock. Corresponding changes need to be made in `secrets -> values` by adding `webconsole` to the disabled plugins list.
- Added a `plugin_available?` check to `_breadcrumb.html.haml` to control the visibility of the WebConsole icon.
- #1425 1425

feat(bedrock): check if plugin webconsole is available

---

app/javascript/widgets/landing_page/components/landingpage/LoginOverlay.jsx
app/javascript/widgets/landing_page/components/landingpage/RegionSelect.jsx
app/javascript/widgets/landing_page/components/layout/PageHead.jsx

This pull request prevents the propagation of click events. If we do not prevent the default behavior of these events, the href value of `#` gets appended to the URL, resulting in a cluttered and unclean appearance. By stopping event propagation, this change ensures that the URL remains tidy and user-friendly.

chore(landingpage): call preventDefault on events to avoid # in urls

---

plugins/compute/app/controllers/compute/instances_controller.rb
plugins/compute/app/views/compute/instances/_item_actions.html.haml
plugins/compute/app/views/compute/instances/confirm_hard_reset.html.haml
plugins/compute/app/views/compute/instances/console.html.haml
plugins/compute/app/views/compute/instances/index.html.haml
plugins/compute/app/views/compute/instances/pre_hard_reset.js.erb

* the web console will load in any case and will show the error message from the backend if the url for the web console cannot be retrieved 
* moved also hard reset button to the object actions
* #1423  cannot hard reset the server from elektra if web console is not loading

fix(instance): fix for hard reset

---

plugins/tools/app/javascript/widgets/castellum/actions/castellum.js
plugins/tools/app/javascript/widgets/castellum/components/error_list.jsx
plugins/tools/app/javascript/widgets/castellum/components/error_row.jsx
plugins/tools/app/javascript/widgets/castellum/containers/error_list.js

Errors in Castellum that are from the type "resize" do not get immediately resolved when the error disappears. It only disappears after another resize attempt on the resource occurs. For this case a new API endpoint was introduced that clears an error from the database early. The follwing changes are present:
- Add new Action column to the resize error table
- Content is a "Clear" button that aims to remove the error from the error list.
- Implement the API endpoint and the caller function
- Refetch existing errors after calling the "Clear" functionality.

Add clear resize error action to admin UI

---

config/initializers/sprockets_processor.rb

this will create the path for assets if not existing

fix(CI): mkdir -p for assets

---

plugins/shared_filesystem_storage/app/javascript/widgets/app/components/castellum/configuration/edit.jsx
plugins/shared_filesystem_storage/app/javascript/widgets/app/components/castellum/configuration/view.jsx

The implementation to set a critical threshold value for autoscaling works, but has the flaw that it does not represent the value as a checked box as an initial value on application start. This PR fixes that.
An example. The existing configuration has threshold crossing active. Before the fix, the checkbox would not have been checked initially.

fix(castellum): Add initial value to threshold crossing

---

config/navigations/services_navigation.rb

This PR removes the permission checks for the Limes UI in the project navigation. Users who lack the resources:project:edit permission cannot edit resources but can still view them. Therefore, we are removing this check to ensure the UI is displayed consistently. The UI itself will handle permission verification where necessary.

chore(resources): do not hide nav item

---

docker/Dockerfile

this will fix the error for init-db:
```
rake aborted!
LoadError: Could not open library '/usr/local/bundle/gems/sassc-2.4.0/ext/libsass.so': Error loading shared library /usr/local/bundle/gems/sassc-2.4.0/ext/libsass.so: No such file or directory
```
there was an update for `ruby:3.2.6-alpine3.20` that needs to add some dev libraries that where present in the older version

fix(ci): fix init-db script

---

app/assets/stylesheets/_monsoon_theme.scss

This PR updates the avatar component to apply the size directly to the `<img>` tag instead of the surrounding `<div>`. This ensures proper image resizing and prevents layout inconsistencies.
- **Updated** `monsoon_theme.scss`: Applied `width` and `height` styles to `.avatar img` for correct scaling.

chore(core): apply avatar image size to img tag

---

app/assets/stylesheets/_monsoon_theme.scss
app/javascript/core/avatar_loader.js

This PR refactors the `loadAvatar` function to ensure it is **truly non-blocking** and does not interfere with other asynchronous operations, such as fetch requests.
Even though the original implementation wrapped image loading in a Promise to try to unblock other requests, this still unintentionally deferred other API calls due to browser network prioritization (the browser tried to load images first). In our case this led to the `auth_projects` call being deferred until after the image load was completed or failed.
This updated implementation leverages `requestIdleCallback()` to defer image loading until the browser is idle, ensuring that fetch requests are not delayed.
- The original implementation used a Promise to handle image loading.
- Since image loading is already …

fix(core): defer avatar img loading to unblock auth_projects fetch

---

plugins/identity/config/initializers/constants.rb
plugins/identity/config/locales/en.yml

Also, for some reason, UI strings for the regular `masterdata_*` roles were missing.
Ref: https://github.com/sapcc/helm-charts/pull/7823

chore(identity): add declarations for `cloud_masterdata_*` roles

---

plugins/identity/app/views/identity/projects/_additional_infos.haml

* this will hide the `edit access-profile` link in the project description if the `access-profile` plugin is dsiabled

feat(access-profile): check for disabled plugin

---

config/navigations/services_navigation.rb
plugins/keymanagerng/app/views/keymanagerng/application/show.html.haml

This PR updates the application to make the new Key Manager UI the default. The old UI cannot be fully removed yet due to shared functionality in the service layer.
- Updated the Main Navigation to link to the new Key Manager UI.
- Removed the dependency on the assets server.
- #1461

chore(key-manager): make new keymanager ui default

---

plugins/networking/app/controllers/networking/routers_controller.rb
plugins/networking/app/javascript/plugin/router.js
plugins/networking/app/models/networking/router.rb
plugins/networking/app/views/networking/routers/new.html.haml

this PR will remove the checks for `fip network` and `subnet` in the create form for routers because these fields are optional from openstack side. The old behavior is to strict and was build in mind that the router is always used to communicate with the outside world. But routers can also be used to bind internal networks together. That was not possible with the old behavior because you must choose a FIP Network and subnet for the router. 
Now it is possible to create just the router without any subnets and add them later

chore(networking): remove the checks for create router

---

plugins/keymanagerng/app/controllers/keymanagerng/application_controller.rb
plugins/keymanagerng/app/javascript/widgets/app/components/secrets/newSecretForm.jsx
plugins/keymanagerng/app/javascript/widgets/app/components/secrets/secretDetails.jsx

In the new key manager UI, the payload content encoding base64 was not displayed based on the selected payload content types. This commit fixes this issue in a way that for all secret types which offer payload content types of "application/pkcs8", "application/pkix-cert", "application/octet-stream", the payload content encoding will be  displayed and set to "base64", same as the old key manager app.
1. NewSecretForm is updated to handle displaying and setting the correct payload content encoding based on the selected payload content type.
2. To add the Project ID alongside the Domain ID in the new Key Manager app same as all other extensions in elektra, I modified the `AjaxController`, which the `ApplicationController` was originally based on, and replaced it with `DashboardController`. …

fix(key-manager): adds base64 payload content encoding for all relevant payload content types in new secret form

---

package.json
plugins/email_service/app/javascript/widgets/maillog-ui/init.js
plugins/email_service/app/views/email_service/maillog/index.html.haml
yarn.lock

This PR migrates the **maillog UI** dependency from **assets-server** to **npm**, in preparation for the **assets-server decommissioning**. The **maillog UI** is now published as an npm package on the GitHub registry under **@sapcc/maillog-ui**. Elektra has been adjusted to consume this package via npm.
- Added **@sapcc/maillog-ui** to `package.json`
- Replaced the script tag source in the view to reference the local npm asset instead of the previous **assets-server** path.
- [#643 ](https://github.com/orgs/sapcc/projects/5/views/6?sliceBy%5Bvalue%5D=Sprint+02%2F25&pane=issue&itemId=80869554&issue=sapcc%7Cjuno%7C643)

chore(email-service): use maillog-ui from npm

---

config/navigations/services_navigation.rb

Set the new Key Manager UI as the default option. The current interface still includes a note with a link to the old UI, allowing users to switch back if needed. Our goal is to gather more feedback from customers and address potential bugs. Eventually, we can consider removing the old UI completely.

chore(key-manager): make the 'new' UI default

---

plugins/compute/app/models/compute/server.rb

* this will fix an issue that when a server was locked with the cli it was not recognized from elektra (when it was locked with elektra it was shown correctly)
* the reason was that the api send two `locked` attributes and only one was checked by elektra
if elektra lockes the server it looks like
````json
"locked": true,
"metadata": {
"locked": "true"
},
````
if the server was locked with cli it looks like
````json
"locked": true,
"metadata": {
"locked": "false"
},
````
elektra was only reading the metadata attribute
* model function for `server.locked?`

fix(compute): check also locked attribute for server lock

---

app/controllers/auth_token_controller.rb
app/views/monsoon_openstack_auth/sessions/_federation.html.haml
config/support/domain_config.yaml

This pull request introduces the initial working implementation of Keystone Federated Authentication. A new view has been created to display a sign-in button for federation, and a corresponding endpoint has been established to receive the authentication token via POST from the Identity Provider.
- **Enhanced Authentication Views**: Introduced a new template: `_federation.html.haml` for the sign-in interface.
- **New Controller Added**: Implemented `auth_token.rb` to handle the reception and verification of the token from the Identity Provider.
- **Additional Views Created**: Developed supplementary views to support the functionality of the `auth_token` controller.
-

feat(core): first working version of identity federation

---

plugins/identity/config/initializers/constants.rb

[Persephone](https://github.wdf.sap.corp/cc/persephone/) (private repo) is a new project/service meant to serve as an "API proxy" to the Gardener API, so that customers can easily set up new Shoots in SCI in a couple straight-forward steps. This change ensures the cloud-level roles needed for its Oslo policy are not available for assigning to users inside the Elektra UI (these should be managed by CAM soon).
Included the cloud-level roles in the block-list. 
None.
None.

feat(config): added "persephone" cloud-level roles to blocklist

---

yarn.lock

Update LimesUI to 1.4.0. Features commitment renewal.
I tested the version with a local elektra deployment and it looks like expected.

chore(deps): update limesui to 1.4.0

---

config/routes.rb

This pull request addresses a bug in the routing logic that was inadvertently introduced by an optimization suggested by RuboCop. Specifically, the optimization replaced string interpolation with <%%>, which led to unexpected behavior in the routes.
- Revert Optimization:
- Restored the original string interpolation syntax to ensure proper functionality of the routes.

fix(core): fixes redirect bug in routes

---

yarn.lock

Update limesUI to 1.5.1. This version contains the juno 3.0.0 upgrade. Additionally it fixes an issue with the commitment renewal functionality. Interactions for this page are now disabled if the user does not have sufficient edit permissions for the resources.

chore(deps): limesui update to 1.5.1

---

plugins/identity/config/initializers/constants.rb
plugins/identity/config/locales/en.yml

This PR adds support for displaying missing LBaaS roles in the user role assignments view.
- Added missing roles to the `ALLOWED_ROLES` list:
- `loadbalancer_admin`
- `loadbalancer_viewer`
- `loadbalancer_poolmemberadmin`
- Added corresponding locale entries for the new role keys
- Fixes #1566

fix(identity): display missing LBaaS roles in user role assignments

---

plugins/shared_filesystem_storage/app/javascript/widgets/app/components/castellum/configuration/view.jsx

The descriptions for the option "min_free_is_critical" were not helpful for the user. This gets changed in this PR.
- Instead of "...resize without delay." the information will be present at the "Autoscaling is enabled:" part of the configuration description. Specifically included in the "Shares will be extended immediately when [...]" section.
How it was previously:
How the description looks like now if critical treshold is enabled in conjuction with "min_free_is_critical":
How the description looks now if only "min_free_is_critical" is set:

fix(ui): fix configuration descriptions for minimum free critical

---

yarn.lock

This is an important one.
* Allows the usage of the UI for external customers, react to domain specific commitment configurations.
* Fix previously broken "canEdit" access checks. The UI assumed a boolean, a string value was delivered instead.
* Fix broken resource bar display for usage only resources, as well as the display for resources that contain commitments but report no capacity by limes due to liquids not being able to assign capacity on openstack backend changes.

chore(deps): update limesui to 1.6.1

---

plugins/compute/app/views/compute/instances/_item_details.html.haml

This PR improves the handling of attached_volumes in the templates by adding guards against nil entries to prevent runtime errors like:
- undefined method 'attachments' for nil:NilClass
- undefined method 'name' for nil:NilClass
- Added guards in the  `_item_details.html.haml` for handling of attached_volumes
- Incident: /incident/ab23289593a2a61094cbb9797bba10de

fix(compute): fix nil-checks in attached_volumes iteration to prevent template errors

---

config/initializers/colorize_logger.rb

* colorize log for development

feat(core): colorize log in development

---

config/support/domain_config.yaml
plugins/image/app/javascript/widgets/app/components/os_images/list.jsx
plugins/image/app/javascript/widgets/app/containers/os_images/list_available.js
plugins/image/app/javascript/widgets/app/containers/os_images/list_suggested.js
plugins/image/app/views/image/ng/images/app.html.haml

* this introduce the possibility to hide public images for specific domain with the `doman_config`
- Issue 1: #1667

feat(image): introduce domain config to hide public images

---

plugins/keymanagerng/app/javascript/widgets/app/components/secrets/secretDetails.jsx

This PR resolves a problem where downloading a secret resulted in a file with unwanted formatting changes. The downloaded file previously included additional double quotes (") around the secret. Moreover, all newlines within the secret were replaced by the literal string \r\n.
- Write the raw secret payload directly to the file, without using` JSON.stringify `or any transformation that would change the content.
- Issue 1: #1621

fix(key-manager): fixes download secret file formatting issue

---

plugins/lbaas2/app/controllers/lbaas2/loadbalancers/listeners_controller.rb
plugins/lbaas2/app/javascript/widgets/app/actions/apiClient.js
plugins/lbaas2/app/javascript/widgets/app/actions/healthMonitor.js
plugins/lbaas2/app/javascript/widgets/app/actions/l7Policy.js
plugins/lbaas2/app/javascript/widgets/app/actions/l7Rule.js
plugins/lbaas2/app/javascript/widgets/app/actions/listener.js
plugins/lbaas2/app/javascript/widgets/app/actions/loadbalancer.js
plugins/lbaas2/app/javascript/widgets/app/actions/pool.js
plugins/lbaas2/config/policy.json
plugins/lbaas2/config/routes.rb
plugins/lbaas2/spec/controllers/listeners_controller_spec.rb
plugins/lbaas2/spec/controllers/members_controller_spec.rb

This PR decouples LBaaS from the old Key Manager plugin by replacing its secret-fetching call with the Elektra osAPI client, enabling safe decommissioning of the plugin.
- Removed the listener actions to fetch secrets and containers (containers was a left over)
- Implement the same login in the listener action to fetch secrets in javascript with the osAPI client.
- Remove all references and tests.

chore(lbaas): switch from keymanager service layer to osAPI

---

docker/Dockerfile

* this will fix the high alert for [rexml](https://avd.aquasec.com/nvd/cve-2025-58767)
* and the medium alert for [puma](https://avd.aquasec.com/nvd/cve-2024-45614)
local trivy check 
`````
trivy image elektra-prod --scanners vuln   
......
elektra-prod (alpine 3.22.1)
Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
`````

chore(core): fix rexml vulnurabillity
