- plugins/networking/app/services/service_layer/networking_service.rb
- plugins/networking/app/views/networking/routers/edit.html.haml
- plugins/networking/app/views/networking/routers/index.html.haml
- plugins/networking/app/views/networking/routers/show.html.haml
> don't raise on router without external gateway

- Gemfile.lock
- app/controllers/dashboard_controller.rb
- app/views/application/_nav.html.haml
- app/views/application/_user_profile.html.haml
- app/views/application/errors/error.html.haml
- app/views/layouts/application.html.haml
- plugins/compute/app/controllers/compute/instances_controller.rb
- plugins/compute/app/controllers/compute/keypairs_controller.rb
> catch SecurityViolation Errors. Add User Profile View

- Gemfile
- Gemfile.lock
- plugins/cost_control/app/assets/javascripts/cost_control/plugin.js
- plugins/cost_control/app/controllers/cost_control/application_controller.rb
- plugins/cost_control/app/controllers/cost_control/cost_object_controller.rb
- plugins/cost_control/app/models/cost_control/billing_object.rb
- plugins/cost_control/app/models/cost_control/kb11n_billing_object.rb
- plugins/cost_control/app/services/service_layer/cost_control_service.rb
- plugins/cost_control/app/views/cost_control/cost_object/_chart.html.erb
- plugins/cost_control/app/views/cost_control/cost_object/_form.html.haml
- plugins/cost_control/app/views/cost_control/cost_object/_table_kb11n_billing_object.html.haml
- plugins/cost_control/app/views/cost_control/cost_object/_table_kb11n_show.html.haml
- plugins/cost_control/app/views/cost_control/cost_object/domain_show.html.haml
- plugins/cost_control/app/views/cost_control/cost_object/index.js.erb
- plugins/cost_control/app/views/cost_control/cost_object/project_show.html.haml
- plugins/cost_control/cost_control.gemspec
- plugins/cost_control/lib/cost_control/driver/fog.rb
- plugins/cost_control/lib/cost_control/driver/interface.rb
- plugins/cost_control/spec/controllers/application_controller_spec.rb
reactivate cost control, better error handling, some updates, bar chart currently disabled
> enhance and reactivate cost control 

- plugins/cost_control/app/services/service_layer/cost_control_service.rb
- plugins/identity/app/views/identity/domains/show.html.haml
- plugins/identity/app/views/identity/projects/shared/_form.html.haml
> disable cost_control if catalog does not contain billing service

- plugins/cost_control/app/controllers/cost_control/application_controller.rb
- plugins/cost_control/app/controllers/cost_control/cost_object_controller.rb
Does this look reasonable @edda ?
> better error messages

- plugins/compute/app/controllers/compute/keypairs_controller.rb
@andypf / @tlesmann : is it intended to be used this way?
> [CCM-294] put user in target for policy check

- plugins/identity/app/controllers/identity/domains/technical_users_controller.rb
- plugins/identity/config/policy.json
> fill policy with domain id for technical users

- plugins/compute/app/controllers/compute/keypairs_controller.rb
- plugins/compute/config/policy.json
> keypair policy: remove not necessary check

- plugins/shared_filesystem_storage/app/controllers/shared_filesystem_storage/application_controller.rb
- plugins/shared_filesystem_storage/config/policy.json
@andypf : and the last of its kind, please have a look
> share policy: check for project scope

- plugins/dns_service/app/controllers/dns_service/zones_controller.rb
- plugins/dns_service/app/models/dns_service/zone.rb
- plugins/dns_service/app/services/service_layer/dns_service_service.rb
> [dns] allow cloud_dns_admin to do zone update/delete at central place

- plugins/cost_control/app/views/cost_control/cost_object/_form.html.haml
Added ll 3. Please merge if this looks reasonable to you @Carthaca .
> check for cost object in payload

- README.md
@edda ok with you or is there more to tell?
> [Readme] add name origin

- plugins/identity/app/views/identity/projects/shared/_form.html.haml
remove cost control from project creation workflow. please merge @majewsky @edda
> remove cost control from project creation

- Gemfile.lock
- plugins/dns_service/app/controllers/dns_service/zones_controller.rb
- plugins/dns_service/app/helpers/dns_service/application_helper.rb
- plugins/dns_service/app/models/dns_service/pool.rb
- plugins/dns_service/app/services/service_layer/dns_service_service.rb
- plugins/dns_service/app/views/dns_service/zones/_zone_item.html.haml
- plugins/dns_service/app/views/dns_service/zones/index.html.haml
- plugins/dns_service/app/views/dns_service/zones/recordsets/_list.html.haml
- plugins/dns_service/app/views/dns_service/zones/recordsets/_recordset_item.html.haml
- plugins/dns_service/app/views/dns_service/zones/recordsets/show.html.haml
- plugins/dns_service/app/views/dns_service/zones/show.html.haml
- plugins/dns_service/config/policy.json
- plugins/dns_service/lib/dns_service/driver/fog.rb
- fog-openstack bump
- moved some uninteresting attributes from list to show
@andypf fyi
> [dns] add pools to cloud_dns_admin view

- config/navigations/cloud_admin_navigation.rb
- config/navigations/compute_admin_navigation.rb
- plugins/compute/app/controllers/compute/host_aggregates_controller.rb
- plugins/compute/app/helpers/compute/hypervisors_helper.rb
- plugins/compute/app/models/compute/host_aggregate.rb
- plugins/compute/app/models/compute/hypervisor.rb
- plugins/compute/app/services/service_layer/compute_service.rb
- plugins/compute/app/views/compute/host_aggregates/_item.html.haml
- plugins/compute/app/views/compute/host_aggregates/index.html.haml
- plugins/compute/app/views/compute/hypervisors/_item.html.haml
- plugins/compute/app/views/compute/hypervisors/index.html.haml
- plugins/compute/app/views/compute/hypervisors/show.html.haml
- plugins/compute/config/policy.json
- plugins/compute/config/routes.rb
- plugins/compute/lib/compute/driver/fog.rb
and improve hypervisor show
@andypf FYI
> [compute] add host aggregates to cloud_admin view

- lib/core/service_layer/model.rb
- plugins/compute/app/views/compute/instances/_item.html.haml
- plugins/compute/app/views/compute/instances/show.html.haml
- plugins/dns_service/app/views/dns_service/zones/recordsets/show.html.haml
- plugins/dns_service/app/views/dns_service/zones/show.html.haml
- plugins/dns_service/app/views/dns_service/zones/transfer_requests/_request.html.haml
- plugins/image/app/views/image/os_images/show.html.haml
and make use of them
@andypf : why can't I use this at https://github.com/sapcc/elektra/blob/master/plugins/shared_filesystem_storage/app/assets/javascripts/shared_filesystem_storage/components/shares/show.coffee#L62 and similar at share_snapshots?
maybe https://github.com/sapcc/elektra/blob/master/plugins/object_storage/app/views/object_storage/objects/show.html.haml#L23 is another candidate
> [core] extend base model with pretty time formatters

- plugins/identity/app/views/identity/projects/request_wizard/new.html.haml
instead of to homepage of docu
> updated link project request to FAQ

- app/assets/javascripts/regions.json
> eu-nl-1 available

- app/helpers/view_helper.rb
- plugins/identity/app/controllers/identity/projects_controller.rb
- plugins/identity/app/views/identity/projects/view.html.haml
- plugins/identity/config/routes.rb
- plugins/lookup/app/controllers/lookup/os_objects_controller.rb
- plugins/lookup/app/views/lookup/os_objects/_good_to_know.html.haml
- plugins/lookup/config/locales/en.yml
- plugins/lookup/config/policy.json
add project view (not as show action because it is already to deeply integrated)
add link to project view if allowed
@edda @andypf FYI
> [lookup] add project lookup by uuid

- plugins/object_storage/app/controllers/object_storage/containers_controller.rb
- plugins/object_storage/app/views/object_storage/containers/_item.html.haml
- plugins/object_storage/app/views/object_storage/containers/confirm_emptying.html.haml
- plugins/object_storage/app/views/object_storage/containers/empty.js.erb
- plugins/object_storage/app/views/object_storage/containers/pre_empty.js.erb
- plugins/object_storage/config/routes.rb
> async emptying for containers

- plugins/block_storage/app/controllers/block_storage/volumes_controller.rb
- plugins/block_storage/app/models/block_storage/volume.rb
- plugins/block_storage/app/views/block_storage/volumes/new_status.html.haml
@andypf : Sorry! I knew this would come back to me - turned out to be very soon :)
> [cinder] allow to reset volume attach_status + hint

- plugins/resource_management/app/controllers/resource_management/domain_admin_controller.rb
- plugins/resource_management/app/views/resource_management/domain_admin/_details_usage_bar.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/review_request.html.haml
> show current resource usage in review request

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js.erb
- app/controllers/dashboard_controller.rb
- app/views/layouts/application.html.haml
- config/routes.rb
> enable policy engine in js context

- plugins/networking/app/services/service_layer/networking_service.rb
DO NOT MERGE YET. NETWORK IS NOT READY!
> DO NOT MERGE UNTIL WE HAVE THE GO -- Quick hack new fip network in EU-DE-1. Fix asap.

- Gemfile.lock
- plugins/networking/app/controllers/networking/floating_ips_controller.rb
- plugins/networking/app/models/networking/floating_ip.rb
- plugins/networking/app/views/networking/floating_ips/_item.html.haml
- plugins/networking/app/views/networking/floating_ips/edit.html.haml
- plugins/networking/app/views/networking/floating_ips/index.html.haml
- plugins/networking/app/views/networking/floating_ips/new.html.haml
- plugins/networking/app/views/networking/floating_ips/update.js.erb
- plugins/networking/config/policy.json
> Floating IPs comment

- app/views/application/_main_toolbar.html.haml
- app/views/layouts/modal.html.haml
Users are confused by this, see Slack this morning.
> less confusing caption

- lib/generators/dashboard_plugin/dashboard_plugin_generator.rb
with that changes I can create a maia or masterdata plugin without problems :-)
> prevent change of classname from plural to singular

- app/helpers/url_helper.rb
- app/views/monsoon_openstack_auth/sessions/new.html.haml
- env.sample
> The CAM url should be configurable, since staging has a different one

- plugins/audit/app/assets/javascripts/audit/actions/events.coffee
- plugins/audit/app/assets/javascripts/audit/components/events/item.coffee
- plugins/audit/app/assets/javascripts/audit/components/events/list.coffee
- plugins/audit/app/assets/javascripts/audit/reducers/events.coffee
I can't claim to have understood the coffee syntax, but I am optimistic that this change might even work ;-) please have a look.
> adapt to latest Hermes API

- plugins/masterdata_cockpit/app/assets/stylesheets/masterdata_cockpit/_application.scss
- plugins/masterdata_cockpit/app/controllers/masterdata_cockpit/project_masterdata_controller.rb
- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_edit_create_js.html.haml
- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_maintain_masterdata.html.haml
- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_masterdata_additional_infos.html.haml
- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_masterdata_details.html.haml
this covers some user feedback
> Masterdata ui fix

- Gemfile
- Gemfile.lock
- lib/core/api_client_manager.rb
- lib/core/elektron_middlewares/pretty_debug.rb
- plugins/dns_service/app/services/service_layer/dns_service_service.rb
- plugins/object_storage/app/services/service_layer/object_storage_service.rb
- plugins/object_storage/app/services/service_layer/object_storage_services/account.rb
- plugins/object_storage/app/services/service_layer/object_storage_services/container.rb
* Uses new version of Elektron (2.0)
* Enables API request middlewares (Elektron 2.0)
* Add a debug middleware to Elektron clients
> Elektron 2.0

- plugins/compute/app/assets/javascripts/compute/fixed_ip.coffee
- plugins/compute/app/controllers/compute/instances_controller.rb
- plugins/compute/app/models/compute/os_interface.rb
- plugins/compute/app/models/compute/server.rb
- plugins/compute/app/views/compute/instances/attach_interface.html.haml
- plugins/compute/app/views/compute/instances/new.html.haml
- plugins/networking/app/services/service_layer/networking_services/port.rb
fixes #206, make it possible to allocate a fixed IP based on network and subnet or select a pre-reserved IP or manually assign an IP.
> Fixed-IP reservation

- plugins/resource_management/app/controllers/resource_management/cloud_admin_controller.rb
- plugins/resource_management/app/models/resource_management/domain.rb
- plugins/resource_management/app/models/resource_management/new_style_resource.rb
- plugins/resource_management/app/services/service_layer/resource_management_service.rb
- plugins/resource_management/app/views/resource_management/application/_details_table_script.js.erb
- plugins/resource_management/app/views/resource_management/application/_sort_details_table_script.js.erb
- plugins/resource_management/app/views/resource_management/cloud_admin/_details_foreign_clusters.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_details_table.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_details_table_row.html.haml
This was harder than expected. Putting this down as a PR so I can review it tomorrow after calming down from my Rails hatred.
> enhance cloud admin resmgmt to edit domain quotas in foreign clusters

- app/assets/stylesheets/_monsoon_theme.scss
- app/views/application/_cloudops_main_toolbar.html.haml
- app/views/application/_cloudops_mega_nav.html.haml
- app/views/application/_cloudops_nav.html.haml
- app/views/layouts/cloudops.html.haml
- plugins/cloudops/app/controllers/cloudops/application_controller.rb
- plugins/cloudops/app/controllers/cloudops/objects_controller.rb
Layout for new cloudops area. This has a new type of "always there" navigation with integrated universal search bar which will eventually be responsive and attach to the left side on very wide screens. 
Additionally the header section is different from our regular layout since we don't need to show the same kind of information or offer the same type of navigation options.
> Cloudops layout

- app/assets/stylesheets/_monsoon_theme.scss
- plugins/compute/app/views/compute/instances/_item.html.haml
- plugins/compute/app/views/compute/instances/index.html.haml
> fixes #269, mark bare metal instances and rework the status icons

- plugins/identity/app/views/identity/domains/show.html.haml
- plugins/lookup/app/controllers/lookup/reverse_lookup_controller.rb
- plugins/lookup/app/javascript/reverse_app/components/app.jsx
- plugins/lookup/spec/controllers/reverse_lookup_controller_spec.rb
Added the possibility to look up instances by instance uuid (in addition to fip and dns).
Fixes #275
> Reverse lookup by instance uuid

- config/initializers/assets.rb
- plugins/automation/app/assets/javascripts/automation/ansi_up.js
- plugins/automation/app/controllers/automation/jobs_controller.rb
- plugins/automation/app/views/automation/jobs/show_data.html.haml
- plugins/automation/app/views/layouts/automation/ansi_app.html.haml
> ANSI color shell output in automation job logs

- plugins/automation/app/controllers/automation/nodes_controller.rb
- plugins/automation/config/locales/en.yml
- plugins/automation/spec/controllers/nodes_controller_spec.rb
It checks if the node has the online fact to true before running an automation.
Fixes: #333
> Run an automation just on online nodes

- Gemfile
- Gemfile.lock
- plugins/identity/app/controllers/identity/projects/role_assignments_controller.rb
- plugins/identity/app/javascript/role_assignments/actions/project_role_assignments.js
- plugins/identity/app/javascript/role_assignments/components/project_role_assignments_form.jsx
- plugins/identity/app/services/service_layer/identity_services/role_assignment.rb
> Extended timeout by removing role groups

- plugins/resource_management/app/controllers/resource_management/project_resources_controller.rb
- plugins/resource_management/app/views/resource_management/project_resources/_bar.html.haml
- plugins/resource_management/app/views/resource_management/project_resources/confirm_reduce_quota.html.haml
> Reduce quota adjustments

- plugins/object_storage/app/controllers/object_storage/containers_controller.rb
- plugins/object_storage/app/controllers/object_storage/folders_controller.rb
- plugins/object_storage/app/controllers/object_storage/objects_controller.rb
- plugins/object_storage/app/helpers/object_storage/application_helper.rb
- plugins/object_storage/app/views/object_storage/application/_object_list_entry.html.haml
- plugins/object_storage/app/views/object_storage/containers/_item.html.haml
- plugins/object_storage/app/views/object_storage/containers/confirm_deletion.html.haml
- plugins/object_storage/app/views/object_storage/containers/confirm_emptying.html.haml
- plugins/object_storage/app/views/object_storage/containers/empty.js.erb
- plugins/object_storage/app/views/object_storage/containers/pre_empty.js.erb
- plugins/object_storage/app/views/object_storage/containers/show.html.haml
- plugins/object_storage/app/views/object_storage/containers/show_access_control.html.haml
- plugins/object_storage/app/views/object_storage/folders/new_folder.html.haml
- plugins/object_storage/app/views/object_storage/folders/new_object.html.haml
- plugins/object_storage/app/views/object_storage/objects/index.html.haml
- plugins/object_storage/app/views/object_storage/objects/move.html.haml
- plugins/object_storage/app/views/object_storage/objects/new_copy.html.haml
- plugins/object_storage/app/views/object_storage/objects/show.html.haml
to support in container/folder/file any kinds of chars (except `/`)
> Object storage and weird names

- plugins/resource_management/app/controllers/resource_management/cloud_admin_controller.rb
- plugins/resource_management/app/views/resource_management/application/_sort_details_table_script.js.erb
- plugins/resource_management/app/views/resource_management/cloud_admin/_details_table.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_domain_quota_overcommitted_details_table.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_project_quota_mismatch_details_table.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_project_quota_overspent_details_table.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/check_inconsistencies.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/check_inconsistencies.js.erb
- plugins/resource_management/app/views/resource_management/cloud_admin/details.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/details.js.erb
add sorting and pagination to inconsistencies view
> more compact check inconsistencies view

- config/environments/development.rb
- env.sample
if you want you can reduce active record logging to a minimum
> option to reduce active record logging

- plugins/resource_management/app/models/resource_management/new_style_resource.rb
- plugins/resource_management/app/views/resource_management/cloud_admin/_area_status_bars.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_bar_row.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_details_table_row.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/_index_status_bars.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/details.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/index.html.haml
- plugins/resource_management/app/views/resource_management/cloud_admin/show_area.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/_area_status_bars.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/_bar_row.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/_details_table_row.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/details.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/index.html.haml
- plugins/resource_management/app/views/resource_management/domain_admin/show_area.html.haml
- plugins/resource_management/app/views/resource_management/project_resources/_bar.html.haml
- plugins/resource_management/app/views/resource_management/project_resources/index.html.haml
- plugins/resource_management/app/views/resource_management/project_resources/show_area.html.haml
Note: it was not possible to test the new flag `externally_managed` directly because I didn't found a project or domain with that kind of resource so I tested it with fake data. Theoretically it should work :-)
> Handle external magaged resources

- config/initializers/filter_parameter_logging.rb
In that way is posible to match any kind of composed params names with the ones defined on the list.
> Filter params by regex expresion

- plugins/identity/app/controllers/identity/projects_controller.rb
- plugins/identity/app/views/identity/projects/api_endpoints.html.haml
- plugins/identity/config/policy.json
- plugins/identity/config/routes.rb
Most of the users use Windows and they always ask on how to convert openrc into the powershell.
> Add openrc support for Windows PowerShell

- plugins/object_storage/app/controllers/object_storage/objects_controller.rb
Non inline downloads should not be html escaped
> object store: Fix downloads

- plugins/kubernetes/app/assets/javascripts/kubernetes/actions/clusters.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/components/clusters/edit.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/components/clusters/events.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/components/clusters/item.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/components/clusters/list.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/components/clusters/new.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/reducers/cluster_form.coffee
- plugins/kubernetes/app/assets/javascripts/kubernetes/reducers/meta_data.coffee
- plugins/kubernetes/app/assets/stylesheets/kubernetes/_kubernetes.scss
While we're at it, also fix some smaller bugs and improve some things.
> Kubernikus add availability zone selection and display

- plugins/identity/config/initializers/constants.rb
- plugins/identity/config/locales/en.yml
Hi @edda,
Please validate this PR.
Regards,
Rajiv
> [Glance-Policy] Adding image_admin and image_viewer roles

- app/javascript/lib/components/datatable.jsx
- lib/core/data_type.rb
- plugins/resources/app/javascript/app/components/cluster/resource.jsx
- plugins/resources/app/javascript/app/components/domain/resource.jsx
Bulk PR for all the small issues I found after deploying #453.
> resources-plugin nitpicks

- plugins/identity/config/initializers/constants.rb
- plugins/identity/config/locales/en.yml
- plugins/networking/config/policy.json
New roles are related to customer requests.
> Added two new roles for securitygroup administration and validation

- Gemfile
- Gemfile.lock
- app/views/application/_breadcrumb.html.haml
- config/navigations/services_navigation.rb
- plugins/webconsole/app/assets/javascripts/webconsole/global/webconsole_container.coffee
- plugins/webconsole/app/assets/stylesheets/webconsole/_application.scss
- plugins/webconsole/app/controllers/webconsole/application_controller.rb
- plugins/webconsole/app/views/webconsole/application/show.html.haml
- plugins/webconsole/config/policy.json
- plugins/webconsole/spec/controllers/application_controller_spec.rb
- plugins/webconsole/webconsole_general_help.md
Revive the web console integration into Elektra.
> Webcli revival

- plugins/identity/config/initializers/constants.rb
- plugins/identity/config/locales/en.yml
- plugins/identity/config/policy.json
Could you please check if this does the job or if more changes are needed?
This is related to https://issues.wdf.sap.corp/browse/CCM-9001
> added support for role_admin and role_viewer

- plugins/identity/app/views/identity/groups/_member.html.haml
- plugins/identity/app/views/identity/groups/_members.html.haml
- plugins/identity/app/views/identity/groups/index.html.haml
- plugins/identity/app/views/identity/groups/show.html.haml
I only disabled the buttons and leave all the backend logic and routes untouched, maybe we need it someday again ;-)
> disable add and edit member

- plugins/compute/config/policy.json
- plugins/identity/config/initializers/constants.rb
- plugins/identity/config/locales/en.yml
- plugins/networking/config/policy.json
Hi @edda 
Please validate and approve this PR.
Regards,
Rajiv
> Policymod for BSO - compute_admin without securitygroup admin

- plugins/networking/config/policy.json
Hi @edda 
Hope this is the last tweak for this request.
Regards,
Rajiv
> [neutron] adding or compute_admin_wsg to context_is_securitygroup_viewer

- plugins/identity/config/initializers/constants.rb
Hi @edda,
Please validate this PR.
Regards,
Rajiv
> [BS] Adding masterdata_viewer role

- lib/core/service_layer/model.rb
- plugins/compute/app/controllers/compute/instances_controller.rb
- plugins/compute/app/models/compute/server.rb
- plugins/compute/app/views/compute/instances/_item.html.haml
all instance actions are secured with `resuce_api_errors` so the errors from the API are no longer hidden and vissible on mouse over status icon.
In case of resize and HV full there is a translation to show a better error message.
> Better servers error handling

- plugins/resources/app/javascript/app/constants.js
@talal Please merge this when you deploy the server group quotas to prod.
> add server group quotas to compute quota package

- config/navigations/cloud_admin_navigation.rb
> [navigation] cloud_admin with only cloud_sharedfilesystem_viewer

- plugins/compute/app/controllers/compute/instances_controller.rb
- plugins/compute/app/helpers/compute/instances_helper.rb
- plugins/compute/app/views/compute/instances/new.html.haml
this will show baremetal images if baremetal flavor was selected and will show vmware images if vmware flavor was selected
> show correct images related to flavor

- plugins/lbaas2/app/javascript/app/components/listeners/ListenerItem.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerList.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/Details.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolItem.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolList.js
- plugins/lbaas2/app/javascript/app/reducers/loadbalancers.js
Added search combined with load of all items for listeners and pools
> [Lbaas2] listener and pool search with loading of all items

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/javascript/app/components/l7Rules/L7RuleList.js
- plugins/lbaas2/app/javascript/app/components/l7Rules/L7RuleListItem.js
- plugins/lbaas2/app/javascript/app/components/l7policies/L7PolicyList.js
- plugins/lbaas2/app/javascript/app/components/l7policies/L7PolicyListItem.js
- plugins/lbaas2/app/javascript/app/components/l7policies/L7PolicySelected.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerItem.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerList.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerItem.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/NewLoadbalancer.js
- plugins/lbaas2/app/javascript/app/components/members/MemberList.js
- plugins/lbaas2/app/javascript/app/components/members/MemberListItem.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolItem.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolList.js
- plugins/lbaas2/app/javascript/app/components/shared/CopyPastePopover.js
- plugins/lbaas2/app/javascript/app/reducers/members.js
- plugins/lbaas2/app/javascript/lib/hooks/useL7Rule.js
- plugins/lbaas2/app/javascript/lib/hooks/useMember.js
> [lbaas2]: search in all lists

- Gemfile
- Gemfile.lock
- docker/Dockerfile
- docker/Dockerfile.integration-tests
> Revert "Update dependency react-rails to ~> 2.6.0"

- plugins/key_manager/app/models/key_manager/secret.rb
> [lbaas2]: Keymanager extended opaque type for octet-stream content

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/controllers/lbaas2/loadbalancers/listeners_controller.rb
- plugins/lbaas2/app/javascript/app/components/listeners/EditListener.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerItem.js
- plugins/lbaas2/app/javascript/app/components/listeners/NewListener.js
- plugins/lbaas2/app/javascript/app/components/pools/EditPool.js
- plugins/lbaas2/app/javascript/app/components/pools/NewPool.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolItem.js
- plugins/lbaas2/app/javascript/lib/hooks/useListener.js
- plugins/lbaas2/app/models/lbaas2/healthmonitor.rb
- plugins/lbaas2/app/models/lbaas2/listener.rb
- plugins/lbaas2/app/models/lbaas2/loadbalancer.rb
- plugins/lbaas2/app/models/lbaas2/member.rb
- plugins/lbaas2/app/models/lbaas2/pool.rb
- plugins/lbaas2/config/policy.json
- plugins/lbaas2/config/routes.rb
- plugins/lbaas2/spec/controllers/listeners_controller_spec.rb
> Lbaas2 pkcs12

- plugins/identity/app/assets/stylesheets/identity/_credentials.scss
- plugins/identity/app/controllers/identity/credentials_controller.rb
- plugins/identity/app/models/identity/os_credential.rb
- plugins/identity/app/services/service_layer/identity_service.rb
- plugins/identity/app/services/service_layer/identity_services/os_credential.rb
- plugins/identity/app/views/identity/credentials/_form.html.haml
- plugins/identity/app/views/identity/credentials/_item.html.haml
- plugins/identity/app/views/identity/credentials/edit.html.haml
- plugins/identity/app/views/identity/credentials/index.html.haml
- plugins/identity/app/views/identity/credentials/new.html.haml
- plugins/identity/config/locales/en.yml
- plugins/identity/config/policy.json
- plugins/identity/config/routes.rb
- plugins/identity/spec/controllers/credentials_controller_spec.rb
if nobody complains, next step is deletion
> comment everything out next step is deletetion

- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerItem.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/shared/Pagination.js
- plugins/lbaas2/app/javascript/app/reducers/loadbalancers.js
- plugins/lbaas2/app/javascript/lib/hooks/useLoadbalancer.js
> [Lbaas2]: load chuncks when lbs searching or clicking all lbs

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/javascript/app/components/healthmonitor/HealthmonitorDetails.js
- plugins/lbaas2/app/javascript/app/components/members/EditMember.js
- plugins/lbaas2/app/javascript/app/components/members/MemberList.js
- plugins/lbaas2/app/javascript/app/components/members/MemberListItem.js
- plugins/lbaas2/app/javascript/app/components/members/NewMember.js
- plugins/lbaas2/app/javascript/app/components/members/NewMemberListItem.js
- plugins/lbaas2/app/javascript/app/components/shared/FormInput.js
- plugins/lbaas2/app/models/lbaas2/member.rb
> lbaas2 member backup

- plugins/lbaas2/app/controllers/lbaas2/loadbalancers_controller.rb
> [LBaas2]: added description to the fips

- plugins/lbaas2/app/javascript/app/components/healthmonitor/EditHealthMonitor.js
- plugins/lbaas2/app/javascript/app/components/healthmonitor/HealthmonitorDetails.js
- plugins/lbaas2/app/javascript/app/components/healthmonitor/NewHealthMonitor.js
Added rewording changes proposed by @m-kratochvil
> [lbaas2]: rewording changes

- plugins/lbaas2/app/javascript/app/components/l7Rules/L7RuleList.js
- plugins/lbaas2/app/javascript/app/components/l7policies/L7PolicyList.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerList.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/members/MemberList.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolList.js
> fixed using special chars with regex

- plugins/identity/config/initializers/constants.rb
- plugins/identity/config/locales/en.yml
> [cronus]: add cronus roles

- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/shared/Pagination.js
- plugins/lbaas2/app/javascript/app/reducers/loadbalancers.js
> Lbaas2 serch reset marker when searching

- plugins/lbaas2/app/javascript/app/components/l7Rules/L7RuleListItem.js
- plugins/lbaas2/app/javascript/app/components/l7policies/L7PolicyListItem.js
- plugins/lbaas2/app/javascript/app/components/listeners/ListenerItem.js
- plugins/lbaas2/app/javascript/app/components/members/MemberListItem.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolItem.js
- plugins/lbaas2/app/javascript/app/components/shared/DropdownMenu.js
> [lbaas2]: custom dropdown menus for scrolling container

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/controllers/lbaas2/loadbalancers/pools/members_controller.rb
- plugins/lbaas2/app/javascript/app/components/members/NewMember.js
> [Lbaas2] display servers matching the ips from the port of the network

- plugins/shared_filesystem_storage/app/javascript/app/components/security_services/form.jsx
- plugins/shared_filesystem_storage/app/javascript/app/components/shares/access_control_form.jsx
- plugins/shared_filesystem_storage/app/javascript/app/components/shares/new.jsx
- plugins/shared_filesystem_storage/app/javascript/app/components/snapshots/new.jsx
> [manila] add ldap security service and multi protocol

- plugins/lbaas2/app/javascript/app/components/healthmonitor/EditHealthMonitor.js
- plugins/lbaas2/app/models/lbaas2/healthmonitor.rb
> Fix healthmonitor edit form for fields: codes, http methods and url path

- app/controllers/dashboard_controller.rb
- app/models/domain_profile.rb
- app/models/user_profile.rb
- app/views/dashboard/accept_terms_of_use.html.haml
- config/settings.yml
Draft of v2 for Terms of Use to be updated in accordance with platform (service) changes and some new regulatory requirements to be clarified.
> Update Terms of Use

- app/views/layouts/application.html.haml
- app/views/layouts/cloudops.html.haml
If this issue is with this fix fixed we should think how to load best the javascript
> dirty hack to check if can get rid of the ‚$ is not defined‘

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/controllers/lbaas2/loadbalancers/pools/healthmonitors_controller.rb
- plugins/lbaas2/app/javascript/app/components/healthmonitor/HealthMonitor.js
- plugins/lbaas2/app/javascript/app/components/healthmonitor/HealthmonitorDetails.js
- plugins/lbaas2/app/javascript/app/components/healthmonitor/HealthmonitorJSON.js
- plugins/lbaas2/app/javascript/app/components/pools/PoolList.js
- plugins/lbaas2/app/javascript/app/components/shared/JsonView.js
- plugins/lbaas2/app/javascript/lib/hooks/useHealthMonitor.js
- plugins/lbaas2/app/javascript/lib/hooks/useLoadbalancer.js
- plugins/lbaas2/app/views/application/lbaas2_widget.html.haml
- Display of allowed adresses pair in the healthmonitor section
- Corrected Plugin name
- JSONView with memorize
- Fetch jus the loadbalancer when vip_port_id not send as param
> Lbaas2 healthmonitor IPs + improvements

- plugins/dns_service/app/controllers/concerns/create_zones_helper.rb
- plugins/dns_service/app/controllers/dns_service/create_zone_wizard_controller.rb
- plugins/dns_service/app/controllers/dns_service/request_zone_wizard_controller.rb
- plugins/dns_service/app/controllers/dns_service/zones_controller.rb
- plugins/dns_service/app/views/dns_service/request_zone_wizard/new.html.haml
this is a fix for the etch case that limes is out of sync
> approve zone and quotas fix

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/javascript/app/components/pools/PoolItem.js
- plugins/lbaas2/app/javascript/lib/hooks/useStatus.js
> customize state label tooltip text

- plugins/lbaas2/app/javascript/app/components/shared/StateLabel.js
- plugins/lbaas2/app/javascript/lib/hooks/useStatus.js
> [LBaaSV2]: shows operating_status error as offline

- plugins/lbaas2/app/assets/stylesheets/lbaas2/_application.scss
- plugins/lbaas2/app/controllers/lbaas2/loadbalancers_controller.rb
- plugins/lbaas2/app/javascript/app/components/l7Rules/EditL7Rule.js
- plugins/lbaas2/app/javascript/app/components/l7Rules/NewL7Rule.js
- plugins/lbaas2/app/javascript/app/components/l7policies/EditL7Policy.js
- plugins/lbaas2/app/javascript/app/components/l7policies/NewL7Policy.js
- plugins/lbaas2/app/javascript/app/components/listeners/EditListener.js
- plugins/lbaas2/app/javascript/app/components/listeners/NewListener.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerItem.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/LoadbalancerList.js
- plugins/lbaas2/app/javascript/app/components/loadbalancers/NewLoadbalancer.js
- plugins/lbaas2/app/javascript/app/components/pools/EditPool.js
- plugins/lbaas2/app/javascript/app/components/pools/NewPool.js
- plugins/lbaas2/app/javascript/app/components/shared/SelectInput.js
- plugins/lbaas2/app/javascript/lib/hooks/useLoadbalancer.js
- plugins/lbaas2/app/models/lbaas2/loadbalancer.rb
- plugins/lbaas2/app/services/service_layer/lbaas2_service.rb
- plugins/lbaas2/app/services/service_layer/lbaas2_services/availability_zone.rb
- plugins/lbaas2/config/policy.json
- plugins/lbaas2/config/routes.rb
- plugins/lbaas2/spec/controllers/loadbalancers_controller_spec.rb
- plugins/lbaas2/spec/controllers/shared.rb
- yarn.lock
> Lbaas2 availability zones

- plugins/networking/app/assets/javascripts/networking/global/floating_ips.coffee
- plugins/networking/app/controllers/networking/networks_controller.rb
- plugins/networking/config/policy.json
> [networking] to get available ips check at least for network viewer role

- plugins/email_service/app/assets/javascripts/email_service/templated_email.js.coffee
- plugins/email_service/app/controllers/email_service/plain_emails_controller.rb
- plugins/email_service/app/controllers/email_service/templated_emails_controller.rb
- plugins/email_service/app/views/email_service/plain_emails/_domain_list.html.haml
- plugins/email_service/app/views/email_service/plain_emails/_form.html.haml
- plugins/email_service/app/views/email_service/templated_emails/_domain_list.html.haml
- plugins/email_service/app/views/email_service/templated_emails/_form.html.haml
* Fixed return_path invalid email address error.
> fix return_path assignment

- config/navigations/cloud_admin_navigation.rb
- plugins/tools/app/controllers/tools/limes_controller.rb
- plugins/tools/app/javascript/limes/actions/limes.js
- plugins/tools/app/javascript/limes/components/application.jsx
- plugins/tools/app/javascript/limes/components/error_list.jsx
- plugins/tools/app/javascript/limes/components/error_row.jsx
- plugins/tools/app/javascript/limes/constants.js
- plugins/tools/app/javascript/limes/containers/error_list.js
- plugins/tools/app/javascript/limes/init.js
- plugins/tools/app/javascript/limes/reducers/index.js
- plugins/tools/app/javascript/limes/reducers/limes.js
- plugins/tools/app/services/service_layer/tools_service.rb
- plugins/tools/app/views/tools/limes/show.html.haml
- plugins/tools/config/policy.json
- plugins/tools/config/routes.rb
This is a carbon copy of the respective UI for Castellum.
> add "Limes Errors" view in cloud admin UI

- plugins/email_service/app/assets/javascripts/email_service/email_source.js.coffee
- plugins/email_service/app/assets/javascripts/email_service/plain_email.js.coffee
- plugins/email_service/app/assets/javascripts/email_service/templated_email.js.coffee
- plugins/email_service/app/controllers/email_service/application_controller.rb
- plugins/email_service/app/controllers/email_service/configsets_controller.rb
- plugins/email_service/app/controllers/email_service/custom_verification_email_templates_controller.rb
- plugins/email_service/app/controllers/email_service/domain_verifications_controller.rb
- plugins/email_service/app/controllers/email_service/ec2_credentials_controller.rb
- plugins/email_service/app/controllers/email_service/email_verifications_controller.rb
- plugins/email_service/app/controllers/email_service/emails_controller.rb
- plugins/email_service/app/controllers/email_service/multicloud_accounts_controller.rb
- plugins/email_service/app/controllers/email_service/plain_emails_controller.rb
- plugins/email_service/app/controllers/email_service/settings_controller.rb
- plugins/email_service/app/controllers/email_service/stats_controller.rb
- plugins/email_service/app/controllers/email_service/templated_emails_controller.rb
- plugins/email_service/app/controllers/email_service/templates_controller.rb
- plugins/email_service/app/controllers/email_service/web_controller.rb
- plugins/email_service/app/validators/json_validator.rb
- plugins/email_service/app/views/email_service/plain_emails/_domain_list.html.haml
- plugins/email_service/app/views/email_service/templated_emails/_domain_list.html.haml
- plugins/email_service/config/routes.rb
- plugins/email_service/spec/controllers/web_controller_spec.rb
- Removed `cloud_support_tools_viewer` role requirement 
- Modified JSON validation to spot empty {}.
> make live & fix json validation

- plugins/compute/app/views/compute/instances/_item_details.html.haml
- plugins/compute/app/views/compute/instances/show.html.haml
> servers: show sizing recommendation

- plugins/identity/config/locales/en.yml
minimalistic role, just for seeing a project
> add reader role to translation

- plugins/identity/config/initializers/constants.rb
accompanies 76f84cd372edec01a64309967f9e433ba0b1ab8d
> add reader to allowed roles

- plugins/lbaas2/app/javascript/widgets/app/components/l7Rules/EditL7Rule.jsx
- plugins/lbaas2/app/javascript/widgets/app/lib/hooks/useL7Rule.jsx
> [lbaas2]: l7 rule removed compare type regex. Warning when editing

- plugins/shared_filesystem_storage/app/javascript/widgets/app/components/castellum/configuration/edit.jsx
- plugins/shared_filesystem_storage/app/javascript/widgets/app/components/castellum/configuration/view.jsx
Based on customer feedback. There was a misunderstanding whether these settings refer to step size or total size.
> clarify wording on autoscaling config UI

- plugins/email_service/app/controllers/email_service/email_verifications_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/javascript/plugin.js
> remove validator and remove sap.com email address check

- e2e/README.md
- plugins/compute/app/javascript/cloud_init_configuration.coffee
- plugins/compute/app/views/compute/instances/_item_details.html.haml
- plugins/compute/app/views/compute/instances/new.html.haml
- plugins/dns_service/app/views/dns_service/request_zone_wizard/new.html.haml
- plugins/dns_service/app/views/dns_service/zones/index.html.haml
- plugins/dns_service/app/views/dns_service/zones/new.html.haml
- plugins/email_service/app/views/email_service/application/index.html.haml
- plugins/email_service/app/views/email_service/domain_verifications/index.html.haml
- plugins/email_service/app/views/email_service/ec2_credentials/index.html.haml
- plugins/email_service/app/views/email_service/email_verifications/index.html.haml
- plugins/email_service/app/views/email_service/emails/index.html.haml
- plugins/email_service/app/views/email_service/settings/index.html.haml
- plugins/email_service/app/views/email_service/web/index.html.haml
- plugins/identity/app/views/identity/domains/show.html.haml
- plugins/identity/app/views/identity/projects/_additional_infos.haml
- plugins/identity/app/views/identity/projects/request_wizard/new.html.haml
- plugins/identity/app/views/identity/projects/shared/_additional_form.html.haml
- plugins/kubernetes/app/views/kubernetes/application/index.html.haml
- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_maintain_masterdata.html.haml
- plugins/masterdata_cockpit/plugin_project_masterdata_help_links.md
- plugins/networking/app/views/networking/backup_networks/index.html.haml
- plugins/resource_management/app/views/resource_management/project_resources/settings.html.haml
Fix broken document links caused by Hugo migration
> fix broken document links

- plugins/email_service/app/controllers/email_service/application_controller.rb
- plugins/email_service/app/controllers/email_service/email_verifications_controller.rb
- plugins/email_service/app/controllers/email_service/plain_emails_controller.rb
- plugins/email_service/app/controllers/email_service/templated_emails_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/models/email_service/forms/plain_email.rb
- plugins/email_service/app/models/email_service/forms/templated_email.rb
- plugins/email_service/app/models/email_service/forms/verified_email.rb
- plugins/email_service/app/views/email_service/domain_verifications/show.html.haml
- plugins/email_service/app/views/email_service/email_verifications/new.html.haml
- plugins/email_service/app/views/email_service/plain_emails/_form.html.haml
- plugins/email_service/app/views/email_service/templated_emails/_form.html.haml
- plugins/email_service/spec/factories/factories.rb
I have immediate bugs to address with this fix. I am configuring rubocop for formatting. I will make a  separate PR for formatting again. @ArtieReus
> configuration set bug fixes

- plugins/dns_service/config/policy.json
Related to: https://github.com/sapcc/helm-charts/commit/499a22d74e07da57b48a0ab7b9a69cdd581e95a0
> [dns] adjust policy to allow sharing operations for any dns_*master

- plugins/metrics/app/controllers/metrics/application_controller.rb
> [metrics] hide grafana

- plugins/lbaas2/app/controllers/lbaas2/loadbalancers/pools/healthmonitors_controller.rb
- plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/EditHealthMonitor.jsx
- plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/HealthmonitorDetails.jsx
- plugins/lbaas2/app/javascript/widgets/app/components/healthmonitor/NewHealthMonitor.jsx
- plugins/lbaas2/app/models/lbaas2/healthmonitor.rb
- plugins/lbaas2/spec/models/healthmonitor_spec.rb
- yarn.lock
> [lbaas] remove timeout

- plugins/audit/app/javascript/widgets/app/components/events/list.jsx
Customer request that time range is confusing. This is an attempt to make it clearer to customers.
> add utc to time range to make clear it's in utc

- app/assets/stylesheets/_monsoon_theme.scss
> Use pointer cursor on paginations

- plugins/resources/app/javascript/widgets/app/components/edit.jsx
> Fix missing space after strong text

- package.json
- plugins/lbaas2/app/javascript/widgets/app/components/Router.jsx
- plugins/lbaas2/app/javascript/widgets/app/components/listeners/AllowedCidrs.jsx
- plugins/lbaas2/app/javascript/widgets/app/components/listeners/CidrsInput.jsx
- plugins/lbaas2/app/javascript/widgets/app/components/listeners/ListenerItem.jsx
- plugins/lbaas2/app/models/lbaas2/listener.rb
- yarn.lock
> [lbaas] add listener cidrs functionality

- plugins/email_service/app/controllers/email_service/application_controller.rb
- plugins/email_service/app/controllers/email_service/emails_controller.rb
- plugins/email_service/app/controllers/email_service/multicloud_accounts_controller.rb
- plugins/email_service/app/controllers/email_service/templates_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/views/email_service/domain_verifications/index.html.haml
- plugins/email_service/app/views/email_service/ec2_credentials/index.html.haml
- plugins/email_service/app/views/email_service/email_verifications/index.html.haml
- plugins/email_service/app/views/email_service/emails/index.html.haml
- plugins/email_service/app/views/email_service/plain_emails/_form.html.haml
- plugins/email_service/app/views/email_service/settings/index.html.haml
- plugins/email_service/app/views/email_service/shared/cronus_activation_warning.html.haml
- plugins/email_service/app/views/email_service/templates/_form.html.haml
- plugins/email_service/app/views/email_service/templates/index.html.haml
- plugins/email_service/spec/factories/factories.rb
- fix broken doc links in email service.
- fix bugs on nebula activation.
- adapt new multi-cloud status during the each state of approval.
> fix bugs on nebula activation and adjust nebula response status

- app/assets/stylesheets/_datatable.scss
- app/javascript/lib/components/datatable.jsx
- plugins/keppel/app/javascript/widgets/app/components/images/details.jsx
- plugins/keppel/app/javascript/widgets/app/components/images/vuln_table.jsx
See individual commit messages for details.
> keppel: various improvements to the vulnerability report UI

- plugins/identity/app/controllers/identity/projects_controller.rb
- plugins/identity/app/models/identity/prodel.rb
- plugins/identity/app/views/identity/projects/check_delete.haml
- Allow supplying bare project id
- Do not accept names starting or ending with whitespace
> Minor prodel improvements

- plugins/keymanagerng/app/javascript/widgets/app/components/secrets/secretDetails.jsx
and show the payload content directly in the secret details panel if the content type is text/plain
> [keymanagerng] Download payload file as a raw file not a json file 

- package.json
- plugins/keymanagerng/app/javascript/widgets/app/components/Application.jsx
- plugins/keymanagerng/app/javascript/widgets/app/components/containers/newContainer.jsx
- plugins/keymanagerng/app/javascript/widgets/app/components/secrets/newSecret.jsx
- plugins/keymanagerng/app/javascript/widgets/app/components/secrets/newSecretForm.jsx
- plugins/keymanagerng/app/javascript/widgets/app/components/secrets/secretDetails.jsx
- yarn.lock
and 
- [SecretDetails] Show the first 500 characters of payload in a codeblock for text/plain content types
- [New Secret] Show expiration time correctly which is always 23:59:59
- [New Secret] Show secret types info as helptext
> [keymanagerng] Show payload download button for all content types

- plugins/email_service/app/controllers/email_service/domain_verifications_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/models/email_service/verified_domain.rb
- plugins/email_service/app/views/email_service/domain_verifications/show.html.haml
> bug fixes to dkim

- config/navigations/services_navigation.rb
- plugins/email_service/app/controllers/email_service/application_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/views/email_service/shared/cronus_unavailable.html.haml
This PR removes the navigation entry and displays information on what are the locations with cronus service.
> restrict cronus unavailable locations

- plugins/identity/app/views/identity/projects/check_delete.haml
This should accommodate the recent schema change in prodel
> prodel: Fix empty resources check

- plugins/resources/app/views/resources/application/show.html.haml
Banner is currently only displayed in QA.
> LimesUI: Display banner on old UI also on production regions

- plugins/compute/app/views/compute/instances/show.html.haml
The other will be 2FA protected soon
> chore(compute-instances): move to thanos internal url

- plugins/email_service/app/controllers/email_service/settings_controller.rb
- plugins/email_service/app/controllers/email_service/web_controller.rb
- plugins/email_service/app/helpers/email_service/application_helper.rb
- plugins/email_service/app/views/email_service/settings/_multicloud.html.haml
- plugins/email_service/app/views/email_service/settings/index.html.haml
- plugins/email_service/app/views/email_service/suppression_lists/index.html.haml
- plugins/email_service/spec/controllers/settings_controller_spec.rb
- replace direct API calls with elektron client
- enhance suppression list to display > 1000 entries with pagination of 250 entries per page.
> fix elektron API calls & enhance suppresion list to display > 1000

- config/navigations/cloud_admin_navigation.rb
- plugins/resources/app/controllers/resources/v2_controller.rb
- plugins/resources/app/views/resources/application/show.html.haml
- plugins/resources/app/views/resources/v2/cluster.html.haml
- plugins/resources/config/routes.rb
This PR aims to release the cluster UI or alternatively named: admin UI of Limes to elektra.
> Limes: Add Cluster UI to elektra

- app/views/application/_main_toolbar.html.haml
replace elektra plugin for quota usage with MFE from limes UI
> feat(quota-usage): replace elektra usage plugin

- docker/Dockerfile.dev
this will handle errors on first boot and exit the start so the user will see what is going on
- in dockerfile to adjust the start script
> fix(dev-env): handle error on first boot

- .github/workflows/ci-checks.yaml
- docker/Dockerfile
* this will remove the test layer in the prod image because we are running the tests now in github actions
* it also updates the postgres from 15 to 16
* and adjusts the github actions to be compatible with `act` to run the actions locally 
- dockerfile: remove test layer and update postgres
- ci-checks.yaml: update actions to V4 and add extra step when running locally with `act`
> chore(docker): remove tests and update postgres 

- plugins/identity/app/views/identity/domains/show.html.haml
restore old behavior that admin do not see the request project entry
> fix(identity): remove request project for admins

- app/controllers/pages_controller.rb
- app/javascript/lib/widget.jsx
- app/javascript/widgets/landing_page/App.jsx
- app/javascript/widgets/landing_page/components/landingpage/DomainSelect.jsx
- app/javascript/widgets/landing_page/components/landingpage/LoginOverlay.jsx
- app/javascript/widgets/landing_page/components/landingpage/RegionSelect.jsx
- app/javascript/widgets/landing_page/components/landingpage/WorldMapQASelect.jsx
- app/javascript/widgets/landing_page/pages/home.jsx
- app/javascript/widgets/landing_page/store.jsx
- app/views/application/_footer.html.haml
- app/views/layouts/noscope.html.haml
- app/views/pages/landing.html.haml
- config/initializers/domain_config.rb
- config/support/domain_config.yaml
- plugins/identity/app/views/identity/domains/show.html.haml
This PR adds a new section to domain_config called `disabled_features` and a new method called `featureHidden?(name)`.
This allows us to hide or show features based on this config.
> feat(bedrock): hide docs and support based on domain config

- plugins/identity/app/controllers/identity/projects_controller.rb
* this will hopefully handle disabled plugins in the project wizard step
#1402
> fix(wizard): check also for plugin_available to filter disabled plugins

- e2e/cypress.config.js
- e2e/run.sh
* this will remove our selfbuild cypress image that was patched to work with `sorry cypress`
* NOTE: we need also adjust our pipeline
> chore(cypress): upgrade cypress and remove self build cypress image

- Gemfile.lock
- README.md
This pull request updates the Elektra installation documentation to reflect the latest versions of key dependencies and provides detailed, step-by-step instructions for setting up the project. 
- Readme
- Gemfile.lock
> chore(docs): reworked Installation for macOS with Updated Dependencies

- app/controllers/application_controller.rb
- app/controllers/scope_controller.rb
- config/initializers/domain_config.rb
- config/initializers/sprockets_processor.rb
* will fix the problem to deliver JS 
* will fix the error page to show the actual error because domain_config is now loaded before
> fix(assets): assets without hash and error message

- config/navigations/services_navigation.rb
- plugins/resources/app/views/resources/v2/project.html.haml
This PR removes the Ressource Management nav link if user has not the required permissions.
> chore(limes): remove ressource link from nav

- docker/Dockerfile
This PR ensures that the image will be rebuilt. The latest image contains some vulnerabilities and should therefore be rebuilt from the base layer to ensure a secure and clean build.
> chore(ci): enforce to rebuild the image

- plugins/keppel/app/javascript/widgets/app/components/accounts/row.jsx
this will fix the link to the related object-storage container in keppel
- Issue: #1465
> fix(keppel): object-storage link in account info

- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_masterdata_details.html.haml
this will disable the propagation information in master-data for now, it will be changed in future
> chore(masterdata-cockpit): disable propagation info for now

- docker/Dockerfile
will fix broken build and removes old stuff
> fix(ci): fix broken build and remove old stuff

- docker/Dockerfile
this will fix the broken deployment
> fix(ci): fix broken deployment

- config/navigations/services_navigation.rb
- config/support/domain_config.yaml
- plugins/networking/app/views/networking/backup_networks/index.html.haml
> feat(networking): make networking backup hideable

- plugins/dns_service/app/services/service_layer/dns_service_services/zone.rb
* this will add a backward compatibility for designate
* it can run on QA with the new version and also on Prod with the older version
* after rollout we can remove it or change the order that the newer version is dried first
> fix(dns-service): backward compatibility for designate

- app/javascript/core/modal.js
- app/javascript/lib/tools/helpers.js
This PR refers to the code scanning [issue](https://github.com/sapcc/elektra/security/code-scanning/48) and may fix it. 
- add a url check
> chore(core): check urls bevore using in modal

- package.json
- yarn.lock
Update LimesUI to 1.3.9. Dependency updates, code optimizations and some fixes.
> chore(deps): limesui update

- app/javascript/core/stateful_links.js
This PR refers to https://github.com/sapcc/elektra/security/code-scanning/11
> chore(core): fix regex in stateful links

- app/controllers/cache_controller.rb
This PR refers to https://github.com/sapcc/elektra/security/code-scanning/8
> chore(core): fix sql query to prevent sql injection

- plugins/compute/app/javascript/fixed_ip.js
- plugins/email_service/app/validators/url_validator.rb
This PR refers to https://github.com/sapcc/elektra/security/code-scanning/6
> chore(core): simplify and extend regex in email

- app/javascript/core/init.js
- plugins/email_service/app/validators/url_validator.rb
- plugins/identity/app/javascript/plugin/project_members.js
- plugins/key_manager/app/javascript/key_manager.js
refers to all DOM text reinterpreted as HTML issues
> chore(core): fixes DOM text reinterpreted as HTML

- plugins/identity/app/controllers/identity/domains_controller.rb
* this will fix the problem to have a named domain and not the id in the path 
* to have the possibility to filter for specific domains
> fix(identity): fix links in project search to use scoped_domain_fid

- Gemfile
- Gemfile.lock
- config/initializers/monsoon_openstack_auth.rb
This PR updates Elektra’s authentication configuration to support a custom regex pattern for natural user names. This ensures that Elektra validates user names according to the specified regex pattern, allowing for greater flexibility and compliance with naming conventions.
- Updated the natural user name pattern in Elektra:  
```ruby
auth.natural_user_name_pattern = /\A([DCIdci]\d*|TI_[A-Za-z0-9]{6}_\w*)\z/
```
> chore(core): customize natural users name regex

- app/assets/stylesheets/_monsoon_theme.scss
* this will adjust the avatar minimal with sizing and edges
> fix(core): avatar edges

- config/navigations/services_navigation.rb
- plugins/keymanagerng/app/views/keymanagerng/application/show.html.haml
This PR reverts changes introduced with the commit 
- #1526
> chore(key-manager): revert changes to make keymanagerng the default

- plugins/access_profile/app/controllers/access_profile/tags_controller.rb
Fixes an issue where the error message was not properly rendered in JSON when the user lacked the required internal role.
- Return json im controller before_action
> chore(access-profile): fixes render unauthorised

- config/navigations/services_navigation.rb
- plugins/audit/app/javascript/widgets/app/components/events/list.jsx
For years, there has been a placeholder error message displayed instead of the actual error. This pull request aims to update it to present the real error message.
> chore(audit): show real error messages in the alert

- app/views/auth_token/redirect.html.haml
* this will change the use of `domain_id` to `domain_name` if we handle the redirect after the federation login
> chore(core): replace domain_id with domain_name because of oauth

- plugins/keppel/app/javascript/widgets/app/components/accounts/row.jsx
- plugins/keppel/app/javascript/widgets/app/components/accounts/upstream_config.jsx
- plugins/keppel/app/javascript/widgets/app/components/gc_policies/edit.jsx
- plugins/keppel/app/javascript/widgets/app/components/images/details.jsx
- plugins/keppel/app/javascript/widgets/app/components/rbac_policies/edit.jsx
- plugins/keppel/app/javascript/widgets/app/components/rbac_policies/row.jsx
- plugins/keppel/app/javascript/widgets/app/components/validation_rules/edit.jsx
Several new features were added to the Keppel API recently. Without this changeset, accounts using those new features will break.
See commit messages.
sapcc/keppel#513 sapcc/keppel#514
Re ForbiddenPermissions in RBAC policies:
> feat(keppel): understand new features added to the Keppel API

- app/javascript/widgets/landing_page/store.jsx
A new Domain "SOV" has been added and needs to be added to the domain list on the landingpage
- Added "SOV" domain to domain list
> chore(ui): add sov domain to domain list

- plugins/dns_service/app/controllers/dns_service/zones_controller.rb
> fix(dns-service): make search intuitive to use

- plugins/identity/app/javascript/widgets/app_credentials/Approuter.jsx
- plugins/identity/app/javascript/widgets/app_credentials/ExpireDate.jsx
- plugins/identity/app/javascript/widgets/app_credentials/Item.jsx
- plugins/identity/app/javascript/widgets/app_credentials/List.jsx
- plugins/identity/app/javascript/widgets/app_credentials/New.jsx
- plugins/identity/app/javascript/widgets/app_credentials/ResponseData.jsx
- plugins/identity/app/javascript/widgets/app_credentials/Show.jsx
- plugins/identity/app/javascript/widgets/app_credentials/styles.scss
* This update includes several live improvements to the Application Credentials UI.
* Improved expiration date rendering with a warning if a credential will expire within 7 days.
* The UI is blocked until the user confirms that they have securely stored the token before closing.
* Additional minor adjustments, such as clarifying the search field description.
> feat(identity): user interface adjustments for app credentials

- plugins/identity/app/javascript/widgets/app_credentials/List.jsx
* the size attr was an artifact that I forgot and produces warnings in the console
> fix(identity): remove wrong size attr

- plugins/shared_filesystem_storage/app/javascript/widgets/app/components/security_services/item.jsx
- plugins/shared_filesystem_storage/app/javascript/widgets/app/components/security_services/list.jsx
* remove status for `security services` list because this field is apparently non-sensical and is removed to not confuse users
* this will close issue [#1571](https://github.com/sapcc/elektra/issues/1571)
> feat(shared-filesystem-storage): remove status from security services

- Gemfile
- Gemfile.lock
- lib/core/elektron_middlewares/debug_logger.rb
this will remove colorize because GNU General Public License v2.0
this was only used in debug information so we removed it
> chore(deps): remove colorize

- yarn.lock
This update introduces sortable table headers for commitments and fixes some navigation issues.
> chore(deps): update limesui to 1.7.0

- plugins/masterdata_cockpit/app/views/masterdata_cockpit/project_masterdata/_maintain_masterdata.html.haml
> chore(masterdata-cockpit): remove outdated link

- .github/workflows/codeql.yml
Disable internal CodeQL setup in fabor of manual workflow:
https://github.com/sapcc/elektra/actions/new?category=security&query=code+scanning
- Merge default workflow configuration with automatic language recognition
> chore(ci): create codeql.yml workflow

- plugins/compute/app/views/compute/instances/new.html.haml
As a part of automation sunset in this PR the automation button from compute is removed.
> chore(automation): removes automation button from compute

- plugins/keppel/app/javascript/widgets/app/components/componentHelpers/TextInput.jsx
- plugins/keppel/app/javascript/widgets/app/components/componentHelpers/TextInput.test.js
This is a fix for: [github.com/SAP-cloud-infrastructure/elektra/pull/1652](https://github.com/SAP-cloud-infrastructure/elektra/pull/1652)
the value variable was not properly adjusted for the component transformation. (line 11 specifically)
> fix(keppel): fix input variable for TextInput

- app/views/monsoon_openstack_auth/sessions/_federation.html.haml
* small optimization to render idp paramter only if available
> feat(identity): render idp only if available

- config/initializers/domain_config.rb
- config/support/domain_config.yaml
- spec/initializers/domain_config_spec.rb
* this will add uri encoding for idp parameter
* adjust default domain config
> feat(identity): idp and uri encoded value

- README.md
* add a note to the README about elektra and vanilla openstack
> chore(core): adjust readme to add information about vanilla openstack

- .github/workflows/checks.yaml
- babel.config.js
- jest.config.js
- jest.setup.js
- package.json
- plugins/kubernetes_ng/app/javascript/widgets/app/components/Breadcrumb.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/components/Breadcrumb.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/components/Card.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/components/Card.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/components/ClipboardText.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/components/ClipboardText.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/mocks/data.ts
- plugins/kubernetes_ng/app/javascript/widgets/app/mocks/getTestRouter.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/-__root.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/-types.ts
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/__root.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/clusters/-components/ClusterCard.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/clusters/-components/ClusterCard.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/clusters/-index.test.tsx
- plugins/kubernetes_ng/app/javascript/widgets/app/routes/clusters/index.tsx
- plugins/kubernetes_ng/app/services/service_layer/kubernetes_ng_services/clusters.rb
- plugins/kubernetes_ng/spec/services/service_layer/kubernetes_ng_services/clusters_spec.rb
- script/lint-plugins.js
- tailwind.config.js
- tsconfig.base.json
- types/jest-dom.d.ts
- yarn.lock
This PR introduces the basic overview of the Kubernetes Gardener clusters page and sets up the testing environment for the component.
- Implemented the components for the Kubernetes clusters overview
- Created test helpers
- Added Jest + React Testing setup and tests
- Issue 1: #ISSUE_ID
> chore(kubernetes): gardener basic overview with test setup and tests

- config/initializers/content_security_policy.rb
> fix(core): adjust csp for webconsole
